<?php

use Illuminate\Database\Seeder;

class LocationsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('locations')->truncate();

        $districts = [
            ['id' => 1, 'parent_id' => null, 'name' => 'Angra Do Heroismo', 'code' => '19'],
            ['id' => 2, 'parent_id' => null, 'name' => 'Aveiro', 'code' => '01'],
            ['id' => 3, 'parent_id' => null, 'name' => 'Beja', 'code' => '02'],
            ['id' => 4, 'parent_id' => null, 'name' => 'Braga', 'code' => '03'],
            ['id' => 5, 'parent_id' => null, 'name' => 'Bragança', 'code' => '04'],
            ['id' => 6, 'parent_id' => null, 'name' => 'Castelo Branco', 'code' => '05'],
            ['id' => 7, 'parent_id' => null, 'name' => 'Coimbra', 'code' => '06'],
            ['id' => 8, 'parent_id' => null, 'name' => 'Évora', 'code' => '07'],
            ['id' => 9, 'parent_id' => null, 'name' => 'Faro', 'code' => '08'],
            ['id' => 10, 'parent_id' => null, 'name' => 'Funchal', 'code' => '22'],
            ['id' => 11, 'parent_id' => null, 'name' => 'Guarda', 'code' => '09'],
            ['id' => 12, 'parent_id' => null, 'name' => 'Horta', 'code' => '20'],
            ['id' => 13, 'parent_id' => null, 'name' => 'Leiria', 'code' => '10'],
            ['id' => 14, 'parent_id' => null, 'name' => 'Lisboa', 'code' => '11'],
            ['id' => 15, 'parent_id' => null, 'name' => 'Ponta Delgada', 'code' => '21'],
            ['id' => 16, 'parent_id' => null, 'name' => 'Portalegre', 'code' => '12'],
            ['id' => 17, 'parent_id' => null, 'name' => 'Porto', 'code' => '13'],
            ['id' => 18, 'parent_id' => null, 'name' => 'Santarém', 'code' => '14'],
            ['id' => 19, 'parent_id' => null, 'name' => 'Setúbal', 'code' => '15'],
            ['id' => 20, 'parent_id' => null, 'name' => 'Viana do Castelo', 'code' => '16'],
            ['id' => 21, 'parent_id' => null, 'name' => 'Vila Real', 'code' => '17'],
            ['id' => 22, 'parent_id' => null, 'name' => 'Viseu', 'code' => '18'],
            /*['parent_id' => null, 'code' => '04', 'name' => 'Bragança'],
            ['parent_id' => null, 'code' => '16', 'name' => 'Viana do Castelo'],
            ['parent_id' => null, 'code' => '17', 'name' => 'Vila Real '],
            ['parent_id' => null, 'code' => '03', 'name' => 'Braga'],
            ['parent_id' => null, 'code' => '13', 'name' => 'Porto'],
            ['parent_id' => null, 'code' => '18', 'name' => 'Viseu'],
            ['parent_id' => null, 'code' => '09', 'name' => 'Guarda'],
            ['parent_id' => null, 'code' => '01', 'name' => 'Aveiro'],
            ['parent_id' => null, 'code' => '06', 'name' => 'Coimbra'],
            ['parent_id' => null, 'code' => '05', 'name' => 'Castelo Branco'],
            ['parent_id' => null, 'code' => '14', 'name' => 'Santarém'],
            ['parent_id' => null, 'code' => '12', 'name' => 'Portalegre'],
            ['parent_id' => null, 'code' => '10', 'name' => 'Leiria'],
            ['parent_id' => null, 'code' => '15', 'name' => 'Setúbal'],
            ['parent_id' => null, 'code' => '11', 'name' => 'Lisboa'],
            ['parent_id' => null, 'code' => '02', 'name' => 'Beja'],
            ['parent_id' => null, 'code' => '07', 'name' => 'Évora'],
            ['parent_id' => null, 'code' => '08', 'name' => 'Faro'],
            ['parent_id' => null, 'code' => '32', 'name' => 'Porto Santo'],
            ['parent_id' => null, 'code' => '31', 'name' => 'Madeira'],
            ['parent_id' => null, 'code' => '42', 'name' => 'São Miguel'],
            ['parent_id' => null, 'code' => '47', 'name' => 'Faial '],
            ['parent_id' => null, 'code' => '41', 'name' => 'Santa Maria'],
            ['parent_id' => null, 'code' => '49', 'name' => 'Corvo'],
            ['parent_id' => null, 'code' => '48', 'name' => 'Flores'],
            ['parent_id' => null, 'code' => '44', 'name' => 'Graciosa'],
            ['parent_id' => null, 'code' => '43', 'name' => 'Terceira'],
            ['parent_id' => null, 'code' => '45', 'name' => 'São Jorge'],
            ['parent_id' => null, 'code' => '46', 'name' => 'Pico']*/
            ];

        $municipalities = [
            ['parent_id' => 1, 'name' => 'Angra do Heorismo', 'code' => '01'],
            ['parent_id' => 1, 'name' => 'Calheta (açores)', 'code' => '02'],
            ['parent_id' => 1, 'name' => 'Santa Cruz da Graciosa', 'code' => '03'],
            ['parent_id' => 1, 'name' => 'Velas', 'code' => '04'],
            ['parent_id' => 1, 'name' => 'Vila Praia da Vitória', 'code' => '05'],
            //Aveiro
            ['parent_id' => 2, 'code' => '01', 'name' => 'Agueda'],
            ['parent_id' => 2, 'code' => '02', 'name' => 'Albergaria-a-velha'],
            ['parent_id' => 2, 'code' => '03', 'name' => 'Anadia'],
            ['parent_id' => 2, 'code' => '04', 'name' => 'Arouca'],
            ['parent_id' => 2, 'code' => '05', 'name' => 'Aveiro'],
            ['parent_id' => 2, 'code' => '06', 'name' => 'Castelo De Paiva'],
            ['parent_id' => 2, 'code' => '07', 'name' => 'Espinho'],
            ['parent_id' => 2, 'code' => '08', 'name' => 'Estarreja'],
            ['parent_id' => 2, 'code' => '10', 'name' => 'Ilhavo'],
            ['parent_id' => 2, 'code' => '11', 'name' => 'Mealhada'],
            ['parent_id' => 2, 'code' => '12', 'name' => 'Murtosa'],
            ['parent_id' => 2, 'code' => '13', 'name' => 'Oliveira De Azemeis'],
            ['parent_id' => 2, 'code' => '14', 'name' => 'Oliveira Do Bairro'],
            ['parent_id' => 2, 'code' => '15', 'name' => 'Ovar'],
            ['parent_id' => 2, 'code' => '16', 'name' => 'S. João Da Madeira'],
            ['parent_id' => 2, 'code' => '09', 'name' => 'Santa Maria Da Feira'],
            ['parent_id' => 2, 'code' => '17', 'name' => 'Sever Do Vouga'],
            ['parent_id' => 2, 'code' => '18', 'name' => 'Vagos'],
            ['parent_id' => 2, 'code' => '19', 'name' => 'Vale De Cambra'],
            //Beja
            ['parent_id' => 3, 'code' => '01', 'name' => 'Aljustrel'],
            ['parent_id' => 3, 'code' => '02', 'name' => 'Almodovar'],
            ['parent_id' => 3, 'code' => '03', 'name' => 'Alvito'],
            ['parent_id' => 3, 'code' => '04', 'name' => 'Barrancos'],
            ['parent_id' => 3, 'code' => '05', 'name' => 'Beja'],
            ['parent_id' => 3, 'code' => '06', 'name' => 'Castro Verde'],
            ['parent_id' => 3, 'code' => '07', 'name' => 'Cuba'],
            ['parent_id' => 3, 'code' => '08', 'name' => 'Ferreira Do Alentejo'],
            ['parent_id' => 3, 'code' => '09', 'name' => 'Mertola'],
            ['parent_id' => 3, 'code' => '10', 'name' => 'Moura'],
            ['parent_id' => 3, 'code' => '11', 'name' => 'Odemira'],
            ['parent_id' => 3, 'code' => '12', 'name' => 'Ourique'],
            ['parent_id' => 3, 'code' => '13', 'name' => 'Serpa'],
            ['parent_id' => 3, 'code' => '14', 'name' => 'Vidigueira'],
            //Braga
            ['parent_id' => 4, 'code' => '01', 'name' => 'Amares'],
            ['parent_id' => 4, 'code' => '02', 'name' => 'Barcelos'],
            ['parent_id' => 4, 'code' => '03', 'name' => 'Braga'],
            ['parent_id' => 4, 'code' => '04', 'name' => 'Cabeceiras De Basto'],
            ['parent_id' => 4, 'code' => '05', 'name' => 'Celorico De Basto'],
            ['parent_id' => 4, 'code' => '06', 'name' => 'Esposende'],
            ['parent_id' => 4, 'code' => '07', 'name' => 'Fafe'],
            ['parent_id' => 4, 'code' => '08', 'name' => 'Guimarães'],
            ['parent_id' => 4, 'code' => '09', 'name' => 'Povoa De Lanhoso'],
            ['parent_id' => 4, 'code' => '10', 'name' => 'Terras De Bouro'],
            ['parent_id' => 4, 'code' => '11', 'name' => 'Vieira Do Minho'],
            ['parent_id' => 4, 'code' => '12', 'name' => 'Vila Nova De Famalicão'],
            ['parent_id' => 4, 'code' => '13', 'name' => 'Vila Verde'],
            ['parent_id' => 4, 'code' => '14', 'name' => 'Vizela'],
            //Bragança
            ['parent_id' => 5, 'code' => '01', 'name' => 'Alfandega Da Fe'],
            ['parent_id' => 5, 'code' => '02', 'name' => 'Bragança'],
            ['parent_id' => 5, 'code' => '03', 'name' => 'Carrazeda De Ansiães'],
            ['parent_id' => 5, 'code' => '04', 'name' => 'Freixo De Espada A Cinta'],
            ['parent_id' => 5, 'code' => '05', 'name' => 'Macedo De Cavaleiros'],
            ['parent_id' => 5, 'code' => '06', 'name' => 'Miranda Do Douro'],
            ['parent_id' => 5, 'code' => '07', 'name' => 'Mirandela'],
            ['parent_id' => 5, 'code' => '08', 'name' => 'Mogadouro'],
            ['parent_id' => 5, 'code' => '09', 'name' => 'Torre De Moncorvo'],
            ['parent_id' => 5, 'code' => '10', 'name' => 'Vila Flor'],
            ['parent_id' => 5, 'code' => '11', 'name' => 'Vimioso'],
            ['parent_id' => 5, 'code' => '12', 'name' => 'Vinhais'],
            //Castelo Branco
            ['parent_id' => 6, 'code' => '01', 'name' => 'Belmonte'],
            ['parent_id' => 6, 'code' => '02', 'name' => 'Castelo Branco'],
            ['parent_id' => 6, 'code' => '03', 'name' => 'Covilhã'],
            ['parent_id' => 6, 'code' => '04', 'name' => 'Fundão'],
            ['parent_id' => 6, 'code' => '05', 'name' => 'Idanha-a-nova'],
            ['parent_id' => 6, 'code' => '06', 'name' => 'Oleiros'],
            ['parent_id' => 6, 'code' => '07', 'name' => 'Penamacor'],
            ['parent_id' => 6, 'code' => '08', 'name' => 'Proença-a-nova'],
            ['parent_id' => 6, 'code' => '09', 'name' => 'Sertã'],
            ['parent_id' => 6, 'code' => '10', 'name' => 'Vila De Rei'],
            ['parent_id' => 6, 'code' => '11', 'name' => 'Vila Velha De Rodão'],
            //Coimbra
            ['parent_id' => 7, 'code' => '01', 'name' => 'Arganil'],
            ['parent_id' => 7, 'code' => '02', 'name' => 'Cantanhede'],
            ['parent_id' => 7, 'code' => '03', 'name' => 'Coimbra'],
            ['parent_id' => 7, 'code' => '04', 'name' => 'Condeixa-a-nova'],
            ['parent_id' => 7, 'code' => '05', 'name' => 'Figueira Da Foz'],
            ['parent_id' => 7, 'code' => '06', 'name' => 'Gois'],
            ['parent_id' => 7, 'code' => '07', 'name' => 'Lousã'],
            ['parent_id' => 7, 'code' => '08', 'name' => 'Mira'],
            ['parent_id' => 7, 'code' => '09', 'name' => 'Miranda Do Corvo'],
            ['parent_id' => 7, 'code' => '10', 'name' => 'Montemor-o-velho'],
            ['parent_id' => 7, 'code' => '11', 'name' => 'Oliveira Do Hospital'],
            ['parent_id' => 7, 'code' => '12', 'name' => 'Pampilhosa Da Serra'],
            ['parent_id' => 7, 'code' => '13', 'name' => 'Penacova'],
            ['parent_id' => 7, 'code' => '14', 'name' => 'Penela'],
            ['parent_id' => 7, 'code' => '15', 'name' => 'Soure'],
            ['parent_id' => 7, 'code' => '16', 'name' => 'Tabua'],
            ['parent_id' => 7, 'code' => '17', 'name' => 'Vila Nova De Poiares'],
            //Evora
            ['parent_id' => 8, 'code' => '01', 'name' => 'Alandroal'],
            ['parent_id' => 8, 'code' => '02', 'name' => 'Arraiolos'],
            ['parent_id' => 8, 'code' => '03', 'name' => 'Borba'],
            ['parent_id' => 8, 'code' => '04', 'name' => 'Estremoz'],
            ['parent_id' => 8, 'code' => '05', 'name' => 'Evora'],
            ['parent_id' => 8, 'code' => '06', 'name' => 'Montemor-o-novo'],
            ['parent_id' => 8, 'code' => '07', 'name' => 'Mora'],
            ['parent_id' => 8, 'code' => '08', 'name' => 'Mourão'],
            ['parent_id' => 8, 'code' => '09', 'name' => 'Portel'],
            ['parent_id' => 8, 'code' => '10', 'name' => 'Redondo'],
            ['parent_id' => 8, 'code' => '11', 'name' => 'Reguengos De Monsaraz'],
            ['parent_id' => 8, 'code' => '12', 'name' => 'Vendas Novas'],
            ['parent_id' => 8, 'code' => '13', 'name' => 'Viana Do Alentejo'],
            ['parent_id' => 8, 'code' => '14', 'name' => 'Vila Viçosa'],
            //Faro
            ['parent_id' => 9, 'code' => '01', 'name' => 'Albufeira'],
            ['parent_id' => 9, 'code' => '02', 'name' => 'Alcoutim'],
            ['parent_id' => 9, 'code' => '03', 'name' => 'Aljezur'],
            ['parent_id' => 9, 'code' => '04', 'name' => 'Castro Marim'],
            ['parent_id' => 9, 'code' => '05', 'name' => 'Faro'],
            ['parent_id' => 9, 'code' => '06', 'name' => 'Lagoa (algarve)'],
            ['parent_id' => 9, 'code' => '07', 'name' => 'Lagos'],
            ['parent_id' => 9, 'code' => '08', 'name' => 'Loule'],
            ['parent_id' => 9, 'code' => '09', 'name' => 'Monchique'],
            ['parent_id' => 9, 'code' => '10', 'name' => 'Olhão'],
            ['parent_id' => 9, 'code' => '11', 'name' => 'Portimão'],
            ['parent_id' => 9, 'code' => '12', 'name' => 'S. Bras De Alportel'],
            ['parent_id' => 9, 'code' => '13', 'name' => 'Silves'],
            ['parent_id' => 9, 'code' => '14', 'name' => 'Tavira'],
            ['parent_id' => 9, 'code' => '15', 'name' => 'Vila Do Bispo'],
            ['parent_id' => 9, 'code' => '16', 'name' => 'Vila Real De Santo Antonio'],
            //Funchal
            ['parent_id' => 10, 'code' => '01', 'name' => 'Calheta (madeira)'],
            ['parent_id' => 10, 'code' => '02', 'name' => 'Camara De Lobos'],
            ['parent_id' => 10, 'code' => '03', 'name' => 'Funchal'],
            ['parent_id' => 10, 'code' => '04', 'name' => 'Machico'],
            ['parent_id' => 10, 'code' => '05', 'name' => 'Ponta Do Sol'],
            ['parent_id' => 10, 'code' => '06', 'name' => 'Porto Moniz'],
            ['parent_id' => 10, 'code' => '07', 'name' => 'Porto Santo'],
            ['parent_id' => 10, 'code' => '08', 'name' => 'Ribeira Brava'],
            ['parent_id' => 10, 'code' => '11', 'name' => 'S. Vicente'],
            ['parent_id' => 10, 'code' => '09', 'name' => 'Santa Cruz'],
            ['parent_id' => 10, 'code' => '10', 'name' => 'Santana'],
            //Guarda
            ['parent_id' => 11, 'code' => '01', 'name' => 'Aguiar Da Beira'],
            ['parent_id' => 11, 'code' => '02', 'name' => 'Almeida'],
            ['parent_id' => 11, 'code' => '03', 'name' => 'Celorico Da Beira'],
            ['parent_id' => 11, 'code' => '04', 'name' => 'Figueira De Castelo Rodrigo'],
            ['parent_id' => 11, 'code' => '05', 'name' => 'Fornos De Algodres'],
            ['parent_id' => 11, 'code' => '06', 'name' => 'Gouveia'],
            ['parent_id' => 11, 'code' => '07', 'name' => 'Guarda'],
            ['parent_id' => 11, 'code' => '08', 'name' => 'Manteigas'],
            ['parent_id' => 11, 'code' => '09', 'name' => 'Meda'],
            ['parent_id' => 11, 'code' => '10', 'name' => 'Pinhel'],
            ['parent_id' => 11, 'code' => '11', 'name' => 'Sabugal'],
            ['parent_id' => 11, 'code' => '12', 'name' => 'Seia'],
            ['parent_id' => 11, 'code' => '13', 'name' => 'Trancoso'],
            ['parent_id' => 11, 'code' => '14', 'name' => 'Vila Nova De Foz Coa'],
            //Horta
            ['parent_id' => 12, 'code' => '01', 'name' => 'Corvo'],
            ['parent_id' => 12, 'code' => '02', 'name' => 'Horta'],
            ['parent_id' => 12, 'code' => '03', 'name' => 'Lajes Das Flores'],
            ['parent_id' => 12, 'code' => '04', 'name' => 'Lajes Do Pico'],
            ['parent_id' => 12, 'code' => '05', 'name' => 'Madalena'],
            ['parent_id' => 12, 'code' => '07', 'name' => 'S. Roque Do Pico'],
            ['parent_id' => 12, 'code' => '06', 'name' => 'Santa Cruz Das Flores'],
            //Leiria
            ['parent_id' => 13, 'code' => '01', 'name' => 'Alcobaça'],
            ['parent_id' => 13, 'code' => '02', 'name' => 'Alvaiazere'],
            ['parent_id' => 13, 'code' => '03', 'name' => 'Ansião'],
            ['parent_id' => 13, 'code' => '04', 'name' => 'Batalha'],
            ['parent_id' => 13, 'code' => '05', 'name' => 'Bombarral'],
            ['parent_id' => 13, 'code' => '06', 'name' => 'Caldas Da Rainha'],
            ['parent_id' => 13, 'code' => '07', 'name' => 'Castanheira De Pera'],
            ['parent_id' => 13, 'code' => '08', 'name' => 'Figueiro Dos Vinhos'],
            ['parent_id' => 13, 'code' => '09', 'name' => 'Leiria'],
            ['parent_id' => 13, 'code' => '10', 'name' => 'Marinha Grande'],
            ['parent_id' => 13, 'code' => '11', 'name' => 'Nazare'],
            ['parent_id' => 13, 'code' => '12', 'name' => 'Obidos'],
            ['parent_id' => 13, 'code' => '13', 'name' => 'Pedrogão Grande'],
            ['parent_id' => 13, 'code' => '14', 'name' => 'Peniche'],
            ['parent_id' => 13, 'code' => '15', 'name' => 'Pombal'],
            ['parent_id' => 13, 'code' => '16', 'name' => 'Porto De Mos'],
            //Lisboa
            ['parent_id' => 14, 'code' => '01', 'name' => 'Alenquer'],
            ['parent_id' => 14, 'code' => '15', 'name' => 'Amadora'],
            ['parent_id' => 14, 'code' => '02', 'name' => 'Arruda Dos Vinhos'],
            ['parent_id' => 14, 'code' => '03', 'name' => 'Azambuja'],
            ['parent_id' => 14, 'code' => '04', 'name' => 'Cadaval'],
            ['parent_id' => 14, 'code' => '05', 'name' => 'Cascais'],
            ['parent_id' => 14, 'code' => '06', 'name' => 'Lisboa'],
            ['parent_id' => 14, 'code' => '07', 'name' => 'Loures'],
            ['parent_id' => 14, 'code' => '08', 'name' => 'Lourinhã'],
            ['parent_id' => 14, 'code' => '09', 'name' => 'Mafra'],
            ['parent_id' => 14, 'code' => '16', 'name' => 'Odivelas'],
            ['parent_id' => 14, 'code' => '10', 'name' => 'Oeiras'],
            ['parent_id' => 14, 'code' => '11', 'name' => 'Sintra'],
            ['parent_id' => 14, 'code' => '12', 'name' => 'Sobral De Monte Agraço'],
            ['parent_id' => 14, 'code' => '13', 'name' => 'Torres Vedras'],
            ['parent_id' => 14, 'code' => '14', 'name' => 'Vila Franca De Xira'],
            //Ponta Delgada
            ['parent_id' => 15, 'code' => '01', 'name' => 'Lagoa (açores)'],
            ['parent_id' => 15, 'code' => '02', 'name' => 'Nordeste'],
            ['parent_id' => 15, 'code' => '03', 'name' => 'Ponta Delgada'],
            ['parent_id' => 15, 'code' => '04', 'name' => 'Povoação'],
            ['parent_id' => 15, 'code' => '05', 'name' => 'Ribeira Grande'],
            ['parent_id' => 15, 'code' => '07', 'name' => 'Vila Do Porto'],
            ['parent_id' => 15, 'code' => '06', 'name' => 'Vila Franca Do Campo'],
            //Portalegre
            ['parent_id' => 16, 'code' => '01', 'name' => 'Alter Do Chão'],
            ['parent_id' => 16, 'code' => '02', 'name' => 'Arronches'],
            ['parent_id' => 16, 'code' => '03', 'name' => 'Avis'],
            ['parent_id' => 16, 'code' => '04', 'name' => 'Campo Maior'],
            ['parent_id' => 16, 'code' => '05', 'name' => 'Castelo De Vide'],
            ['parent_id' => 16, 'code' => '06', 'name' => 'Crato'],
            ['parent_id' => 16, 'code' => '07', 'name' => 'Elvas'],
            ['parent_id' => 16, 'code' => '08', 'name' => 'Fronteira'],
            ['parent_id' => 16, 'code' => '09', 'name' => 'Gavião'],
            ['parent_id' => 16, 'code' => '10', 'name' => 'Marvão'],
            ['parent_id' => 16, 'code' => '11', 'name' => 'Monforte'],
            ['parent_id' => 16, 'code' => '12', 'name' => 'Nisa'],
            ['parent_id' => 16, 'code' => '13', 'name' => 'Ponte De Sor'],
            ['parent_id' => 16, 'code' => '14', 'name' => 'Portalegre'],
            ['parent_id' => 16, 'code' => '15', 'name' => 'Sousel'],
            //Porto
            ['parent_id' => 17, 'code' => '01', 'name' => 'Amarante'],
            ['parent_id' => 17, 'code' => '02', 'name' => 'Baião'],
            ['parent_id' => 17, 'code' => '03', 'name' => 'Felgueiras'],
            ['parent_id' => 17, 'code' => '04', 'name' => 'Gondomar'],
            ['parent_id' => 17, 'code' => '05', 'name' => 'Lousada'],
            ['parent_id' => 17, 'code' => '06', 'name' => 'Maia'],
            ['parent_id' => 17, 'code' => '07', 'name' => 'Marco De Canaveses'],
            ['parent_id' => 17, 'code' => '08', 'name' => 'Matosinhos'],
            ['parent_id' => 17, 'code' => '09', 'name' => 'Paços De Ferreira'],
            ['parent_id' => 17, 'code' => '10', 'name' => 'Paredes'],
            ['parent_id' => 17, 'code' => '11', 'name' => 'Penafiel'],
            ['parent_id' => 17, 'code' => '12', 'name' => 'Porto'],
            ['parent_id' => 17, 'code' => '13', 'name' => 'Povoa De Varzim'],
            ['parent_id' => 17, 'code' => '14', 'name' => 'Santo Tirso'],
            ['parent_id' => 17, 'code' => '18', 'name' => 'Trofa'],
            ['parent_id' => 17, 'code' => '15', 'name' => 'Valongo'],
            ['parent_id' => 17, 'code' => '16', 'name' => 'Vila Do Conde'],
            ['parent_id' => 17, 'code' => '17', 'name' => 'Vila Nova De Gaia'],
            //Santarém
            ['parent_id' => 18, 'code' => '01', 'name' => 'Abrantes'],
            ['parent_id' => 18, 'code' => '02', 'name' => 'Alcanena'],
            ['parent_id' => 18, 'code' => '03', 'name' => 'Almeirim'],
            ['parent_id' => 18, 'code' => '04', 'name' => 'Alpiarça'],
            ['parent_id' => 18, 'code' => '05', 'name' => 'Benavente'],
            ['parent_id' => 18, 'code' => '06', 'name' => 'Cartaxo'],
            ['parent_id' => 18, 'code' => '07', 'name' => 'Chamusca'],
            ['parent_id' => 18, 'code' => '08', 'name' => 'Constancia'],
            ['parent_id' => 18, 'code' => '09', 'name' => 'Coruche'],
            ['parent_id' => 18, 'code' => '10', 'name' => 'Entroncamento'],
            ['parent_id' => 18, 'code' => '11', 'name' => 'Ferreira Do Zezere'],
            ['parent_id' => 18, 'code' => '12', 'name' => 'Golegã'],
            ['parent_id' => 18, 'code' => '13', 'name' => 'Mação'],
            ['parent_id' => 18, 'code' => '21', 'name' => 'Ourem'],
            ['parent_id' => 18, 'code' => '14', 'name' => 'Rio Maior'],
            ['parent_id' => 18, 'code' => '15', 'name' => 'Salvaterra De Magos'],
            ['parent_id' => 18, 'code' => '16', 'name' => 'Santarem'],
            ['parent_id' => 18, 'code' => '17', 'name' => 'Sardoal'],
            ['parent_id' => 18, 'code' => '18', 'name' => 'Tomar'],
            ['parent_id' => 18, 'code' => '19', 'name' => 'Torres Novas'],
            ['parent_id' => 18, 'code' => '20', 'name' => 'Vila Nova Da Barquinha'],
            //Setubal
            ['parent_id' => 19, 'code' => '01', 'name' => 'Alcacer Do Sal'],
            ['parent_id' => 19, 'code' => '02', 'name' => 'Alcochete'],
            ['parent_id' => 19, 'code' => '03', 'name' => 'Almada'],
            ['parent_id' => 19, 'code' => '04', 'name' => 'Barreiro'],
            ['parent_id' => 19, 'code' => '05', 'name' => 'Grandola'],
            ['parent_id' => 19, 'code' => '06', 'name' => 'Moita'],
            ['parent_id' => 19, 'code' => '07', 'name' => 'Montijo'],
            ['parent_id' => 19, 'code' => '08', 'name' => 'Palmela'],
            ['parent_id' => 19, 'code' => '09', 'name' => 'Santiago Do Cacem'],
            ['parent_id' => 19, 'code' => '10', 'name' => 'Seixal'],
            ['parent_id' => 19, 'code' => '11', 'name' => 'Sesimbra'],
            ['parent_id' => 19, 'code' => '12', 'name' => 'Setubal'],
            ['parent_id' => 19, 'code' => '13', 'name' => 'Sines'],
            //Viana do Castelo
            ['parent_id' => 20, 'code' => '01', 'name' => 'Arcos De Valdevez'],
            ['parent_id' => 20, 'code' => '02', 'name' => 'Caminha'],
            ['parent_id' => 20, 'code' => '03', 'name' => 'Melgaço'],
            ['parent_id' => 20, 'code' => '04', 'name' => 'Monção'],
            ['parent_id' => 20, 'code' => '05', 'name' => 'Paredes De Coura'],
            ['parent_id' => 20, 'code' => '06', 'name' => 'Ponte Da Barca'],
            ['parent_id' => 20, 'code' => '07', 'name' => 'Ponte De Lima'],
            ['parent_id' => 20, 'code' => '08', 'name' => 'Valença'],
            ['parent_id' => 20, 'code' => '09', 'name' => 'Viana Do Castelo'],
            ['parent_id' => 20, 'code' => '10', 'name' => 'Vila Nova De Cerveira'],
            //Vila Real
            ['parent_id' => 21, 'code' => '01', 'name' => 'Alijo'],
            ['parent_id' => 21, 'code' => '02', 'name' => 'Boticas'],
            ['parent_id' => 21, 'code' => '03', 'name' => 'Chaves'],
            ['parent_id' => 21, 'code' => '04', 'name' => 'Mesão Frio'],
            ['parent_id' => 21, 'code' => '05', 'name' => 'Mondim De Basto'],
            ['parent_id' => 21, 'code' => '06', 'name' => 'Montalegre'],
            ['parent_id' => 21, 'code' => '07', 'name' => 'Murça'],
            ['parent_id' => 21, 'code' => '08', 'name' => 'Peso Da Regua'],
            ['parent_id' => 21, 'code' => '09', 'name' => 'Ribeira De Pena'],
            ['parent_id' => 21, 'code' => '10', 'name' => 'Sabrosa'],
            ['parent_id' => 21, 'code' => '11', 'name' => 'Santa Marta De Penaguião'],
            ['parent_id' => 21, 'code' => '12', 'name' => 'Valpaços'],
            ['parent_id' => 21, 'code' => '13', 'name' => 'Vila Pouca De Aguiar'],
            ['parent_id' => 21, 'code' => '14', 'name' => 'Vila Real'],
            //Viseu
            ['parent_id' => 22, 'code' => '01', 'name' => 'Armamar'],
            ['parent_id' => 22, 'code' => '02', 'name' => 'Carregal Do Sal'],
            ['parent_id' => 22, 'code' => '03', 'name' => 'Castro Daire'],
            ['parent_id' => 22, 'code' => '04', 'name' => 'Cinfães'],
            ['parent_id' => 22, 'code' => '05', 'name' => 'Lamego'],
            ['parent_id' => 22, 'code' => '06', 'name' => 'Mangualde'],
            ['parent_id' => 22, 'code' => '07', 'name' => 'Moimenta Da Beira'],
            ['parent_id' => 22, 'code' => '08', 'name' => 'Mortagua'],
            ['parent_id' => 22, 'code' => '09', 'name' => 'Nelas'],
            ['parent_id' => 22, 'code' => '10', 'name' => 'Oliveira De Frades'],
            ['parent_id' => 22, 'code' => '11', 'name' => 'Penalva Do Castelo'],
            ['parent_id' => 22, 'code' => '12', 'name' => 'Penedono'],
            ['parent_id' => 22, 'code' => '13', 'name' => 'Resende'],
            ['parent_id' => 22, 'code' => '15', 'name' => 'S. João Da Pesqueira'],
            ['parent_id' => 22, 'code' => '16', 'name' => 'S. Pedro Do Sul'],
            ['parent_id' => 22, 'code' => '14', 'name' => 'Santa Comba Dão'],
            ['parent_id' => 22, 'code' => '17', 'name' => 'Satão'],
            ['parent_id' => 22, 'code' => '18', 'name' => 'Sernancelhe'],
            ['parent_id' => 22, 'code' => '19', 'name' => 'Tabuaço'],
            ['parent_id' => 22, 'code' => '20', 'name' => 'Tarouca'],
            ['parent_id' => 22, 'code' => '21', 'name' => 'Tondela'],
            ['parent_id' => 22, 'code' => '22', 'name' => 'Vila Nova De Paiva'],
            ['parent_id' => 22, 'code' => '23', 'name' => 'Viseu'],
            ['parent_id' => 22, 'code' => '24', 'name' => 'Vouzela'],

            ];

        DB::table('locations')->insert($districts);
        DB::table('locations')->insert($municipalities);
    }
}
