<?php

use Illuminate\Database\Seeder;

class VehiclesMakesModelsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('vehicles_makes_models')->delete();

        $makes = [
            ['id' => 1, 'name' => 'Abarth', 'parent_id' => null],
            ['id' => 2, 'name' => 'Acura', 'parent_id' => null],
            ['id' => 3, 'name' => 'Alfa Romeo', 'parent_id' => null],
            ['id' => 4, 'name' => 'Aston Martin', 'parent_id' => null],
            ['id' => 5, 'name' => 'Audi', 'parent_id' => null],
            ['id' => 6, 'name' => 'Austin', 'parent_id' => null],
            ['id' => 7, 'name' => 'Bentley', 'parent_id' => null],
            ['id' => 8, 'name' => 'BMW', 'parent_id' => null],
            ['id' => 9, 'name' => 'Cadillac', 'parent_id' => null],
            ['id' => 10, 'name' => 'Chevrolet', 'parent_id' => null],
            ['id' => 11, 'name' => 'Chrysler', 'parent_id' => null],
            ['id' => 12, 'name' => 'Citroën', 'parent_id' => null],
            ['id' => 13, 'name' => 'Corvette', 'parent_id' => null],
            ['id' => 14, 'name' => 'Dacia', 'parent_id' => null],
            ['id' => 15, 'name' => 'Daihatsu', 'parent_id' => null],
            ['id' => 16, 'name' => 'Dodge', 'parent_id' => null],
            ['id' => 17, 'name' => 'Ferrari', 'parent_id' => null],
            ['id' => 18, 'name' => 'Fiat', 'parent_id' => null],
            ['id' => 19, 'name' => 'Ford', 'parent_id' => null],
            ['id' => 20, 'name' => 'Honda', 'parent_id' => null],
            ['id' => 21, 'name' => 'Hummer', 'parent_id' => null],
            ['id' => 22, 'name' => 'Hyundai', 'parent_id' => null],
            ['id' => 23, 'name' => 'Isuzu', 'parent_id' => null],
            ['id' => 24, 'name' => 'Iveco', 'parent_id' => null],
            ['id' => 25, 'name' => 'Jaguar', 'parent_id' => null],
            ['id' => 26, 'name' => 'Jeep', 'parent_id' => null],
            ['id' => 27, 'name' => 'Kia', 'parent_id' => null],
            ['id' => 28, 'name' => 'Lada', 'parent_id' => null],
            ['id' => 29, 'name' => 'Lamborghini', 'parent_id' => null],
            ['id' => 30, 'name' => 'Lancia', 'parent_id' => null],
            ['id' => 31, 'name' => 'Land Rover', 'parent_id' => null],
            ['id' => 32, 'name' => 'Lexus', 'parent_id' => null],
            ['id' => 33, 'name' => 'Lincoln', 'parent_id' => null],
            ['id' => 34, 'name' => 'Lotus', 'parent_id' => null],
            ['id' => 35, 'name' => 'Maserati', 'parent_id' => null],
            ['id' => 36, 'name' => 'Maybach', 'parent_id' => null],
            ['id' => 37, 'name' => 'Mazda', 'parent_id' => null],
            ['id' => 38, 'name' => 'Mercedes', 'parent_id' => null],
            ['id' => 39, 'name' => 'MG', 'parent_id' => null],
            ['id' => 40, 'name' => 'Mini', 'parent_id' => null],
            ['id' => 41, 'name' => 'Mitsubishi', 'parent_id' => null],
            ['id' => 42, 'name' => 'Morgan', 'parent_id' => null],
            ['id' => 43, 'name' => 'Nissan', 'parent_id' => null],
            ['id' => 44, 'name' => 'Opel', 'parent_id' => null],
            ['id' => 45, 'name' => 'Peugeot', 'parent_id' => null],
            ['id' => 46, 'name' => 'Piaggio', 'parent_id' => null],
            ['id' => 47, 'name' => 'Pontiac', 'parent_id' => null],
            ['id' => 48, 'name' => 'Porsche', 'parent_id' => null],
            ['id' => 49, 'name' => 'Renault', 'parent_id' => null],
            ['id' => 50, 'name' => 'Rolls Royce', 'parent_id' => null],
            ['id' => 51, 'name' => 'Rover', 'parent_id' => null],
            ['id' => 52, 'name' => 'Saab', 'parent_id' => null],
            ['id' => 53, 'name' => 'Seat', 'parent_id' => null],
            ['id' => 54, 'name' => 'Skoda', 'parent_id' => null],
            ['id' => 55, 'name' => 'Smart', 'parent_id' => null],
            ['id' => 56, 'name' => 'Ssangyong', 'parent_id' => null],
            ['id' => 57, 'name' => 'Subaru', 'parent_id' => null],
            ['id' => 58, 'name' => 'Suzuki', 'parent_id' => null],
            ['id' => 59, 'name' => 'Tata', 'parent_id' => null],
            ['id' => 60, 'name' => 'Toyota', 'parent_id' => null],
            ['id' => 61, 'name' => 'Triumph', 'parent_id' => null],
            ['id' => 62, 'name' => 'Volvo', 'parent_id' => null],
            ['id' => 63, 'name' => 'Volkswagen', 'parent_id' => null],
        ];

        $models = [
            // Abarth
            ['name' => '500C', 'parent_id' => 1],

            // Acura
            ['name' => 'EL', 'parent_id' => 2],

            // Alfa Romeo
            ['name' => '145', 'parent_id' => 3],
            ['name' => '146', 'parent_id' => 3],
            ['name' => '147', 'parent_id' => 3],
            ['name' => '147 GTA', 'parent_id' => 3],
            ['name' => '155', 'parent_id' => 3],
            ['name' => '156', 'parent_id' => 3],
            ['name' => '159', 'parent_id' => 3],
            ['name' => '164', 'parent_id' => 3],
            ['name' => '166', 'parent_id' => 3],
            ['name' => '2000', 'parent_id' => 3],
            ['name' => '33', 'parent_id' => 3],
            ['name' => '75', 'parent_id' => 3],
            ['name' => '8C Spider', 'parent_id' => 3],
            ['name' => 'Alfasud', 'parent_id' => 3],
            ['name' => 'Alfetta', 'parent_id' => 3],
            ['name' => 'Brera', 'parent_id' => 3],
            ['name' => 'Giulia', 'parent_id' => 3],
            ['name' => 'Giulietta', 'parent_id' => 3],
            ['name' => 'GT', 'parent_id' => 3],
            ['name' => 'GTV', 'parent_id' => 3],
            ['name' => 'MiTo', 'parent_id' => 3],
            ['name' => 'Spider', 'parent_id' => 3],
            ['name' => 'Sprint', 'parent_id' => 3],

            // Aston Martin
            ['name' => 'Cygnet', 'parent_id' => 4],
            ['name' => 'DB7', 'parent_id' => 4],
            ['name' => 'DB9', 'parent_id' => 4],
            ['name' => 'DBS', 'parent_id' => 4],
            ['name' => 'V8', 'parent_id' => 4],
            ['name' => 'Vanquish', 'parent_id' => 4],
            ['name' => 'Vantage', 'parent_id' => 4],

            // Audi
            ['name' => '100', 'parent_id' => 5],
            ['name' => '50', 'parent_id' => 5],
            ['name' => '80', 'parent_id' => 5],
            ['name' => '90', 'parent_id' => 5],
            ['name' => 'A1', 'parent_id' => 5],
            ['name' => 'A1 Cabriolet', 'parent_id' => 5],
            ['name' => 'A1 Sportback', 'parent_id' => 5],
            ['name' => 'A2', 'parent_id' => 5],
            ['name' => 'A3', 'parent_id' => 5],
            ['name' => 'A3 Cabriolet', 'parent_id' => 5],
            ['name' => 'A3 Sportback', 'parent_id' => 5],
            ['name' => 'A4', 'parent_id' => 5],
            ['name' => 'A4 Allroad', 'parent_id' => 5],
            ['name' => 'A4 Cabriolet', 'parent_id' => 5],
            ['name' => 'A5', 'parent_id' => 5],
            ['name' => 'A5 Cabriolet', 'parent_id' => 5],
            ['name' => 'A5 Sportback', 'parent_id' => 5],
            ['name' => 'A6', 'parent_id' => 5],
            ['name' => 'A6 Allroad', 'parent_id' => 5],
            ['name' => 'A7', 'parent_id' => 5],
            ['name' => 'A7 Sportback', 'parent_id' => 5],
            ['name' => 'A8', 'parent_id' => 5],
            ['name' => 'Cabriolet', 'parent_id' => 5],
            ['name' => 'Coupé', 'parent_id' => 5],
            ['name' => 'Q3', 'parent_id' => 5],
            ['name' => 'Q5', 'parent_id' => 5],
            ['name' => 'Q7', 'parent_id' => 5],
            ['name' => 'Quattro', 'parent_id' => 5],
            ['name' => 'R8 Coupé', 'parent_id' => 5],
            ['name' => 'RS4', 'parent_id' => 5],
            ['name' => 'RS6', 'parent_id' => 5],
            ['name' => 'S3', 'parent_id' => 5],
            ['name' => 'S4', 'parent_id' => 5],
            ['name' => 'S5', 'parent_id' => 5],
            ['name' => 'TT', 'parent_id' => 5],
            ['name' => 'TT Roadster', 'parent_id' => 5],
            ['name' => 'TTS', 'parent_id' => 5],

            // Austin
            ['name' => '1300', 'parent_id' => 6],
            ['name' => 'Metro', 'parent_id' => 6],
            ['name' => 'Mini', 'parent_id' => 6],

            // Bentley
            ['name' => 'Arnage', 'parent_id' => 7],
            ['name' => 'Continental', 'parent_id' => 7],
            ['name' => 'Continental Flying Spur', 'parent_id' => 7],
            ['name' => 'Continental GT', 'parent_id' => 7],
            ['name' => 'Eight', 'parent_id' => 7],
            ['name' => 'Turbo R', 'parent_id' => 7],

            // BMW
            ['name' => '114', 'parent_id' => 8],
            ['name' => '116', 'parent_id' => 8],
            ['name' => '118', 'parent_id' => 8],
            ['name' => '120', 'parent_id' => 8],
            ['name' => '123', 'parent_id' => 8],
            ['name' => '125', 'parent_id' => 8],
            ['name' => '118 Cabriolet', 'parent_id' => 8],
            ['name' => '120 Cabriolet', 'parent_id' => 8],
            ['name' => '123 Cabriolet', 'parent_id' => 8],
            ['name' => '118 Coupé', 'parent_id' => 8],
            ['name' => '120 Coupé', 'parent_id' => 8],
            ['name' => '123 Coupé', 'parent_id' => 8],
            ['name' => '216', 'parent_id' => 8],
            ['name' => '218', 'parent_id' => 8],
            ['name' => '220', 'parent_id' => 8],
            ['name' => '315', 'parent_id' => 8],
            ['name' => '316', 'parent_id' => 8],
            ['name' => '318', 'parent_id' => 8],
            ['name' => '320', 'parent_id' => 8],
            ['name' => '323', 'parent_id' => 8],
            ['name' => '324', 'parent_id' => 8],
            ['name' => '325', 'parent_id' => 8],
            ['name' => '328', 'parent_id' => 8],
            ['name' => '330', 'parent_id' => 8],
            ['name' => '335', 'parent_id' => 8],
            ['name' => 'ActiveHybrid 3', 'parent_id' => 8],
            ['name' => 'M3', 'parent_id' => 8],
            ['name' => '316 Compact', 'parent_id' => 8],
            ['name' => '318 Compact', 'parent_id' => 8],
            ['name' => '318 Cabriolet', 'parent_id' => 8],
            ['name' => '320 Cabriolet', 'parent_id' => 8],
            ['name' => '323 Cabriolet', 'parent_id' => 8],
            ['name' => '325 Cabriolet', 'parent_id' => 8],
            ['name' => '328 Cabriolet', 'parent_id' => 8],
            ['name' => '330 Cabriolet', 'parent_id' => 8],
            ['name' => '335 Cabriolet', 'parent_id' => 8],
            ['name' => 'M3 Cabriolet', 'parent_id' => 8],
            ['name' => '318 Gran Turismo', 'parent_id' => 8],
            ['name' => '320 Gran Turismo', 'parent_id' => 8],
            ['name' => '418', 'parent_id' => 8],
            ['name' => '420', 'parent_id' => 8],
            ['name' => '425', 'parent_id' => 8],
            ['name' => '435', 'parent_id' => 8],
            ['name' => 'M4', 'parent_id' => 8],
            ['name' => '518', 'parent_id' => 8],
            ['name' => '520', 'parent_id' => 8],
            ['name' => '523', 'parent_id' => 8],
            ['name' => '524', 'parent_id' => 8],
            ['name' => '525', 'parent_id' => 8],
            ['name' => '528', 'parent_id' => 8],
            ['name' => '530', 'parent_id' => 8],
            ['name' => '535', 'parent_id' => 8],
            ['name' => '545', 'parent_id' => 8],
            ['name' => 'M5', 'parent_id' => 8],
            ['name' => 'M550', 'parent_id' => 8],
            ['name' => '520 Gran Turismo', 'parent_id' => 8],
            ['name' => '530 Gran Turismo', 'parent_id' => 8],
            ['name' => '535 Gran Turismo', 'parent_id' => 8],
            ['name' => '630', 'parent_id' => 8],
            ['name' => '633', 'parent_id' => 8],
            ['name' => '635', 'parent_id' => 8],
            ['name' => '640', 'parent_id' => 8],
            ['name' => '645', 'parent_id' => 8],
            ['name' => '650', 'parent_id' => 8],
            ['name' => 'M6', 'parent_id' => 8],
            ['name' => '630 Cabriolet', 'parent_id' => 8],
            ['name' => '635 Cabriolet', 'parent_id' => 8],
            ['name' => '640 Cabriolet', 'parent_id' => 8],
            ['name' => '645 Cabriolet', 'parent_id' => 8],
            ['name' => 'M6 Cabriolet', 'parent_id' => 8],
            ['name' => '725', 'parent_id' => 8],
            ['name' => '728', 'parent_id' => 8],
            ['name' => '730', 'parent_id' => 8],
            ['name' => '730L', 'parent_id' => 8],
            ['name' => '735', 'parent_id' => 8],
            ['name' => '735L', 'parent_id' => 8],
            ['name' => '740', 'parent_id' => 8],
            ['name' => '740L', 'parent_id' => 8],
            ['name' => '745', 'parent_id' => 8],
            ['name' => '750', 'parent_id' => 8],
            ['name' => '760L', 'parent_id' => 8],
            ['name' => 'ActiveHybrid 7', 'parent_id' => 8],
            ['name' => '850', 'parent_id' => 8],
            ['name' => 'M1', 'parent_id' => 8],
            ['name' => 'Z3 M', 'parent_id' => 8],
            ['name' => 'Z4 M', 'parent_id' => 8],
            ['name' => 'X1', 'parent_id' => 8],
            ['name' => 'X3', 'parent_id' => 8],
            ['name' => 'X4', 'parent_id' => 8],
            ['name' => 'X5', 'parent_id' => 8],
            ['name' => 'X6', 'parent_id' => 8],
            ['name' => 'Z3', 'parent_id' => 8],
            ['name' => 'Z4', 'parent_id' => 8],
            ['name' => '1600', 'parent_id' => 8],
            ['name' => '1602', 'parent_id' => 8],
            ['name' => '501', 'parent_id' => 8],
            ['name' => '502', 'parent_id' => 8],
            ['name' => 'i3', 'parent_id' => 8],
            ['name' => 'i8', 'parent_id' => 8],

            // Cadillac
            ['name' => 'Escalade', 'parent_id' => 9],

            // Chevrolet
            ['name' => '150', 'parent_id' => 10],
            ['name' => '2500', 'parent_id' => 10],
            ['name' => 'Aveo', 'parent_id' => 10],
            ['name' => 'Camaro', 'parent_id' => 10],
            ['name' => 'Captiva', 'parent_id' => 10],
            ['name' => 'Corvette C4', 'parent_id' => 10],
            ['name' => 'Corvette C5', 'parent_id' => 10],
            ['name' => 'Coupé', 'parent_id' => 10],
            ['name' => 'Cruze', 'parent_id' => 10],
            ['name' => 'Epica', 'parent_id' => 10],
            ['name' => 'Lacetti', 'parent_id' => 10],
            ['name' => 'Lanos', 'parent_id' => 10],
            ['name' => 'Matiz', 'parent_id' => 10],
            ['name' => 'Nexia', 'parent_id' => 10],
            ['name' => 'Nubira', 'parent_id' => 10],
            ['name' => 'Orlando', 'parent_id' => 10],
            ['name' => 'Spark', 'parent_id' => 10],
            ['name' => 'SSR', 'parent_id' => 10],
            ['name' => 'Tacuma', 'parent_id' => 10],
            ['name' => 'Tahoe', 'parent_id' => 10],
            ['name' => 'Trax', 'parent_id' => 10],

            // Chrysler
            ['name' => '300C', 'parent_id' => 11],
            ['name' => '300M', 'parent_id' => 11],
            ['name' => 'Crossfire', 'parent_id' => 11],
            ['name' => 'Grand Voyager', 'parent_id' => 11],
            ['name' => 'Neon', 'parent_id' => 11],
            ['name' => 'PT Cruiser', 'parent_id' => 11],
            ['name' => 'Sebring', 'parent_id' => 11],
            ['name' => 'Sebring Cabriolet', 'parent_id' => 11],
            ['name' => 'Stratus', 'parent_id' => 11],
            ['name' => 'Voyager', 'parent_id' => 11],

            // Citroën
            ['name' => '2CV', 'parent_id' => 12],
            ['name' => 'AX', 'parent_id' => 12],
            ['name' => 'Berlingo', 'parent_id' => 12],
            ['name' => 'BX', 'parent_id' => 12],
            ['name' => 'C1', 'parent_id' => 12],
            ['name' => 'C2', 'parent_id' => 12],
            ['name' => 'C25', 'parent_id' => 12],
            ['name' => 'C3', 'parent_id' => 12],
            ['name' => 'C3 Picasso', 'parent_id' => 12],
            ['name' => 'C3 Pluriel', 'parent_id' => 12],
            ['name' => 'C4', 'parent_id' => 12],
            ['name' => 'C4 Cactus', 'parent_id' => 12],
            ['name' => 'C4 Picasso', 'parent_id' => 12],
            ['name' => 'C5', 'parent_id' => 12],
            ['name' => 'C6', 'parent_id' => 12],
            ['name' => 'C8', 'parent_id' => 12],
            ['name' => 'C-Crosser', 'parent_id' => 12],
            ['name' => 'CX', 'parent_id' => 12],
            ['name' => 'C-zero', 'parent_id' => 12],
            ['name' => 'DS', 'parent_id' => 12],
            ['name' => 'DS3', 'parent_id' => 12],
            ['name' => 'DS4', 'parent_id' => 12],
            ['name' => 'DS5', 'parent_id' => 12],
            ['name' => 'Evasion', 'parent_id' => 12],
            ['name' => 'Grand C4 Picasso', 'parent_id' => 12],
            ['name' => 'Jumper', 'parent_id' => 12],
            ['name' => 'Jumpy', 'parent_id' => 12],
            ['name' => 'Méhari', 'parent_id' => 12],
            ['name' => 'Nemo', 'parent_id' => 12],
            ['name' => 'Saxo', 'parent_id' => 12],
            ['name' => 'Visa', 'parent_id' => 12],
            ['name' => 'Xantia', 'parent_id' => 12],
            ['name' => 'XM', 'parent_id' => 12],
            ['name' => 'Xsara', 'parent_id' => 12],
            ['name' => 'Xsara Picasso', 'parent_id' => 12],
            ['name' => 'ZX', 'parent_id' => 12],

            // Corvette
            ['name' => 'C6', 'parent_id' => 13],

            // Dacia
            ['name' => 'Duster', 'parent_id' => 14],
            ['name' => 'Lodgy', 'parent_id' => 14],
            ['name' => 'Logan', 'parent_id' => 14],
            ['name' => 'Sandero', 'parent_id' => 14],

            // Daihatsu
            ['name' => 'Charade', 'parent_id' => 15],
            ['name' => 'Cuore', 'parent_id' => 15],
            ['name' => 'Rocky', 'parent_id' => 15],
            ['name' => 'Sirion', 'parent_id' => 15],
            ['name' => 'Terios', 'parent_id' => 15],
            ['name' => 'YRV', 'parent_id' => 15],

            // Dodge
            ['name' => 'Caliber', 'parent_id' => 16],
            ['name' => 'Durango', 'parent_id' => 16],
            ['name' => 'Journey', 'parent_id' => 16],
            ['name' => 'Ram', 'parent_id' => 16],

            // Ferrari
            ['name' => '348', 'parent_id' => 17],
            ['name' => '360', 'parent_id' => 17],
            ['name' => '458', 'parent_id' => 17],
            ['name' => '575', 'parent_id' => 17],
            ['name' => '612', 'parent_id' => 17],
            ['name' => 'California', 'parent_id' => 17],
            ['name' => 'F355', 'parent_id' => 17],
            ['name' => 'F430', 'parent_id' => 17],
            ['name' => 'FF', 'parent_id' => 17],

            // Fiat
            ['name' => '500', 'parent_id' => 18],
            ['name' => '500 Abarth', 'parent_id' => 18],
            ['name' => '500C', 'parent_id' => 18],
            ['name' => '500L', 'parent_id' => 18],
            ['name' => '500X', 'parent_id' => 18],
            ['name' => 'Grande Punto', 'parent_id' => 18],
            ['name' => 'Punto', 'parent_id' => 18],
            ['name' => 'Punto Cabriolet', 'parent_id' => 18],
            ['name' => 'Punto Evo', 'parent_id' => 18],
            ['name' => '1200', 'parent_id' => 18],
            ['name' => '124', 'parent_id' => 18],
            ['name' => '127', 'parent_id' => 18],
            ['name' => '128', 'parent_id' => 18],
            ['name' => '131', 'parent_id' => 18],
            ['name' => '1900', 'parent_id' => 18],
            ['name' => '750', 'parent_id' => 18],
            ['name' => '8V', 'parent_id' => 18],
            ['name' => 'Barchetta', 'parent_id' => 18],
            ['name' => 'Brava', 'parent_id' => 18],
            ['name' => 'Bravo', 'parent_id' => 18],
            ['name' => 'Cinquecento', 'parent_id' => 18],
            ['name' => 'Coupé', 'parent_id' => 18],
            ['name' => 'Croma', 'parent_id' => 18],
            ['name' => 'Doblò', 'parent_id' => 18],
            ['name' => 'Ducato', 'parent_id' => 18],
            ['name' => 'Ducato 14', 'parent_id' => 18],
            ['name' => 'Ducato 33', 'parent_id' => 18],
            ['name' => 'Fiorino', 'parent_id' => 18],
            ['name' => 'Freemont', 'parent_id' => 18],
            ['name' => 'Idea', 'parent_id' => 18],
            ['name' => 'Linea', 'parent_id' => 18],
            ['name' => 'Marea', 'parent_id' => 18],
            ['name' => 'Multipla', 'parent_id' => 18],
            ['name' => 'Palio', 'parent_id' => 18],
            ['name' => 'Panda', 'parent_id' => 18],
            ['name' => 'Regata', 'parent_id' => 18],
            ['name' => 'Ritmo', 'parent_id' => 18],
            ['name' => 'Scudo', 'parent_id' => 18],
            ['name' => 'Seicento', 'parent_id' => 18],
            ['name' => 'Stilo', 'parent_id' => 18],
            ['name' => 'Strada', 'parent_id' => 18],
            ['name' => 'Tempra', 'parent_id' => 18],
            ['name' => 'Tipo', 'parent_id' => 18],
            ['name' => 'Ulysse', 'parent_id' => 18],
            ['name' => 'Uno', 'parent_id' => 18],

            // Ford
            ['name' => '300', 'parent_id' => 19],
            ['name' => 'B-MAX', 'parent_id' => 19],
            ['name' => 'Capri', 'parent_id' => 19],
            ['name' => 'C-MAX', 'parent_id' => 19],
            ['name' => 'Consul', 'parent_id' => 19],
            ['name' => 'Cougar', 'parent_id' => 19],
            ['name' => 'Custom', 'parent_id' => 19],
            ['name' => 'Deluxe', 'parent_id' => 19],
            ['name' => 'Ecosport', 'parent_id' => 19],
            ['name' => 'Escort', 'parent_id' => 19],
            ['name' => 'Escort Cabriolet', 'parent_id' => 19],
            ['name' => 'Explorer', 'parent_id' => 19],
            ['name' => 'Fiesta', 'parent_id' => 19],
            ['name' => 'Focus', 'parent_id' => 19],
            ['name' => 'Focus Cabriolet', 'parent_id' => 19],
            ['name' => 'Fusion', 'parent_id' => 19],
            ['name' => 'Galaxy', 'parent_id' => 19],
            ['name' => 'Granada', 'parent_id' => 19],
            ['name' => 'Grand C-Max', 'parent_id' => 19],
            ['name' => 'Ka', 'parent_id' => 19],
            ['name' => 'Kuga', 'parent_id' => 19],
            ['name' => 'Maverick', 'parent_id' => 19],
            ['name' => 'Mondeo', 'parent_id' => 19],
            ['name' => 'Mustang', 'parent_id' => 19],
            ['name' => 'Orion', 'parent_id' => 19],
            ['name' => 'Pinto', 'parent_id' => 19],
            ['name' => 'Probe', 'parent_id' => 19],
            ['name' => 'Puma', 'parent_id' => 19],
            ['name' => 'Ranger', 'parent_id' => 19],
            ['name' => 'Scorpio', 'parent_id' => 19],
            ['name' => 'Sierra', 'parent_id' => 19],
            ['name' => 'S-MAX', 'parent_id' => 19],
            ['name' => 'StreetKa', 'parent_id' => 19],
            ['name' => 'T', 'parent_id' => 19],
            ['name' => 'Taunus', 'parent_id' => 19],
            ['name' => 'Taurus', 'parent_id' => 19],
            ['name' => 'Tourneo', 'parent_id' => 19],
            ['name' => 'Transit', 'parent_id' => 19],
            ['name' => 'Transit 280S', 'parent_id' => 19],

            // Honda
            ['name' => 'Accord', 'parent_id' => 20],
            ['name' => 'Civic', 'parent_id' => 20],
            ['name' => 'Concerto', 'parent_id' => 20],
            ['name' => 'CR-V', 'parent_id' => 20],
            ['name' => 'CR-X', 'parent_id' => 20],
            ['name' => 'CR-Z', 'parent_id' => 20],
            ['name' => 'HR-V', 'parent_id' => 20],
            ['name' => 'Insight', 'parent_id' => 20],
            ['name' => 'Integra', 'parent_id' => 20],
            ['name' => 'Jazz', 'parent_id' => 20],
            ['name' => 'Legend', 'parent_id' => 20],
            ['name' => 'NSX', 'parent_id' => 20],
            ['name' => 'Prelude', 'parent_id' => 20],
            ['name' => 'S2000', 'parent_id' => 20],
            ['name' => 'Stream', 'parent_id' => 20],

            // Hummer
            ['name' => 'H2', 'parent_id' => 21],
            ['name' => 'H3', 'parent_id' => 21],

            // Hyundai
            ['name' => 'Accent', 'parent_id' => 22],
            ['name' => 'Atos', 'parent_id' => 22],
            ['name' => 'Coupé', 'parent_id' => 22],
            ['name' => 'Elantra', 'parent_id' => 22],
            ['name' => 'Galloper', 'parent_id' => 22],
            ['name' => 'Getz', 'parent_id' => 22],
            ['name' => 'H-1', 'parent_id' => 22],
            ['name' => 'H 100', 'parent_id' => 22],
            ['name' => 'i10', 'parent_id' => 22],
            ['name' => 'i20', 'parent_id' => 22],
            ['name' => 'i30', 'parent_id' => 22],
            ['name' => 'i40', 'parent_id' => 22],
            ['name' => 'ix20', 'parent_id' => 22],
            ['name' => 'ix35', 'parent_id' => 22],
            ['name' => 'Lantra', 'parent_id' => 22],
            ['name' => 'Matrix', 'parent_id' => 22],
            ['name' => 'Pony', 'parent_id' => 22],
            ['name' => 'Santa Fe', 'parent_id' => 22],
            ['name' => 'S-Coupe', 'parent_id' => 22],
            ['name' => 'Sonata', 'parent_id' => 22],
            ['name' => 'Trajet', 'parent_id' => 22],
            ['name' => 'Tucson', 'parent_id' => 22],
            ['name' => 'Veloster', 'parent_id' => 22],

            // Isuzu
            ['name' => 'D-Max', 'parent_id' => 23],
            ['name' => 'Trooper', 'parent_id' => 23],

            // Iveco
            ['name' => '35.12', 'parent_id' => 24],
            ['name' => 'Daily', 'parent_id' => 24],

            // Jaguar
            ['name' => 'F-Type', 'parent_id' => 25],
            ['name' => 'MK II', 'parent_id' => 25],
            ['name' => 'S-Type', 'parent_id' => 25],
            ['name' => 'XF', 'parent_id' => 25],
            ['name' => 'XJ', 'parent_id' => 25],
            ['name' => 'XJ12', 'parent_id' => 25],
            ['name' => 'XJ6', 'parent_id' => 25],
            ['name' => 'XJ8', 'parent_id' => 25],
            ['name' => 'XJR', 'parent_id' => 25],
            ['name' => 'XJS', 'parent_id' => 25],
            ['name' => 'XK', 'parent_id' => 25],
            ['name' => 'XK8', 'parent_id' => 25],
            ['name' => 'XKR', 'parent_id' => 25],
            ['name' => 'X-type', 'parent_id' => 25],

            // Jeep
            ['name' => 'Cherokee', 'parent_id' => 26],
            ['name' => 'Compass', 'parent_id' => 26],
            ['name' => 'Grand Cherokee', 'parent_id' => 26],
            ['name' => 'Patriot', 'parent_id' => 26],
            ['name' => 'Renegade', 'parent_id' => 26],
            ['name' => 'Willys', 'parent_id' => 26],
            ['name' => 'Wrangler', 'parent_id' => 26],

            // Kia
            ['name' => 'Bongo', 'parent_id' => 27],
            ['name' => 'Carens', 'parent_id' => 27],
            ['name' => 'Carnival', 'parent_id' => 27],
            ['name' => 'Cee\'d', 'parent_id' => 27],
            ['name' => 'Cerato', 'parent_id' => 27],
            ['name' => 'Clarus', 'parent_id' => 27],
            ['name' => 'Magentis', 'parent_id' => 27],
            ['name' => 'Optima', 'parent_id' => 27],
            ['name' => 'Picanto', 'parent_id' => 27],
            ['name' => 'Rio', 'parent_id' => 27],
            ['name' => 'Sephia', 'parent_id' => 27],
            ['name' => 'Shuma', 'parent_id' => 27],
            ['name' => 'Sorento', 'parent_id' => 27],
            ['name' => 'Soul', 'parent_id' => 27],
            ['name' => 'Sportage', 'parent_id' => 27],
            ['name' => 'Venga', 'parent_id' => 27],

            // Lada
            ['name' => '110', 'parent_id' => 28],
            ['name' => 'Niva', 'parent_id' => 28],

            // Lamborghini
            ['name' => 'Gallardo', 'parent_id' => 29],

            // Lancia
            ['name' => 'Beta', 'parent_id' => 30],
            ['name' => 'Dedra', 'parent_id' => 30],
            ['name' => 'Delta', 'parent_id' => 30],
            ['name' => 'Flavia', 'parent_id' => 30],
            ['name' => 'Fulvia', 'parent_id' => 30],
            ['name' => 'Kappa', 'parent_id' => 30],
            ['name' => 'Lybra', 'parent_id' => 30],
            ['name' => 'Musa', 'parent_id' => 30],
            ['name' => 'Phedra', 'parent_id' => 30],
            ['name' => 'Prisma', 'parent_id' => 30],
            ['name' => 'Thema', 'parent_id' => 30],
            ['name' => 'Thesis', 'parent_id' => 30],
            ['name' => 'Ypsilon', 'parent_id' => 30],

            // Land Rover
            ['name' => 'Defender', 'parent_id' => 31],
            ['name' => 'Discovery', 'parent_id' => 31],
            ['name' => 'Discovery 2', 'parent_id' => 31],
            ['name' => 'Discovery 3', 'parent_id' => 31],
            ['name' => 'Freelander', 'parent_id' => 31],
            ['name' => 'Freelander 2', 'parent_id' => 31],
            ['name' => 'Range Rover', 'parent_id' => 31],
            ['name' => 'Range Rover Evoque', 'parent_id' => 31],
            ['name' => 'Range Rover Sport', 'parent_id' => 31],

            // Lexus
            ['name' => 'CT200h', 'parent_id' => 32],
            ['name' => 'GS300', 'parent_id' => 32],
            ['name' => 'IS200', 'parent_id' => 32],
            ['name' => 'IS200d', 'parent_id' => 32],
            ['name' => 'IS220d', 'parent_id' => 32],
            ['name' => 'IS250', 'parent_id' => 32],
            ['name' => 'IS300h', 'parent_id' => 32],
            ['name' => 'NX300h', 'parent_id' => 32],
            ['name' => 'RX300', 'parent_id' => 32],
            ['name' => 'RX400h', 'parent_id' => 32],
            ['name' => 'RX450h', 'parent_id' => 32],

            // Lincoln
            ['name' => 'Town Car', 'parent_id' => 33],

            // Lotus
            ['name' => 'Elan', 'parent_id' => 34],
            ['name' => 'Elise', 'parent_id' => 34],

            // Maserati
            ['name' => '3200', 'parent_id' => 35],
            ['name' => '422', 'parent_id' => 35],
            ['name' => 'Coupé', 'parent_id' => 35],
            ['name' => 'Ghibli', 'parent_id' => 35],
            ['name' => 'GranCabrio', 'parent_id' => 35],
            ['name' => 'GranSport', 'parent_id' => 35],
            ['name' => 'Quattroporte', 'parent_id' => 35],

            // Maybach
            ['name' => '57', 'parent_id' => 36],

            // Mazda
            ['name' => '121', 'parent_id' => 37],
            ['name' => '2', 'parent_id' => 37],
            ['name' => '3', 'parent_id' => 37],
            ['name' => '323', 'parent_id' => 37],
            ['name' => '323F', 'parent_id' => 37],
            ['name' => '5', 'parent_id' => 37],
            ['name' => '6', 'parent_id' => 37],
            ['name' => '626', 'parent_id' => 37],
            ['name' => 'BT-50', 'parent_id' => 37],
            ['name' => 'CX-3', 'parent_id' => 37],
            ['name' => 'CX-5', 'parent_id' => 37],
            ['name' => 'CX-7', 'parent_id' => 37],
            ['name' => 'Demio', 'parent_id' => 37],
            ['name' => 'MPV', 'parent_id' => 37],
            ['name' => 'MX3', 'parent_id' => 37],
            ['name' => 'MX5', 'parent_id' => 37],
            ['name' => 'MX6', 'parent_id' => 37],
            ['name' => 'Premacy', 'parent_id' => 37],
            ['name' => 'RX7', 'parent_id' => 37],
            ['name' => 'RX8', 'parent_id' => 37],

            // Mercedes
            ['name' => 'A140', 'parent_id' => 38],
            ['name' => 'A150', 'parent_id' => 38],
            ['name' => 'A160', 'parent_id' => 38],
            ['name' => 'A170', 'parent_id' => 38],
            ['name' => 'A180', 'parent_id' => 38],
            ['name' => 'A190', 'parent_id' => 38],
            ['name' => 'A200', 'parent_id' => 38],
            ['name' => 'A220', 'parent_id' => 38],
            ['name' => 'A250', 'parent_id' => 38],
            ['name' => 'A45 AMG', 'parent_id' => 38],
            ['name' => 'B150', 'parent_id' => 38],
            ['name' => 'B160', 'parent_id' => 38],
            ['name' => 'B170', 'parent_id' => 38],
            ['name' => 'B180', 'parent_id' => 38],
            ['name' => 'B200', 'parent_id' => 38],
            ['name' => 'C180', 'parent_id' => 38],
            ['name' => 'C200', 'parent_id' => 38],
            ['name' => 'C220', 'parent_id' => 38],
            ['name' => 'C230', 'parent_id' => 38],
            ['name' => 'C250', 'parent_id' => 38],
            ['name' => 'C270', 'parent_id' => 38],
            ['name' => 'C280', 'parent_id' => 38],
            ['name' => 'C300', 'parent_id' => 38],
            ['name' => 'C30 AMG', 'parent_id' => 38],
            ['name' => 'C320', 'parent_id' => 38],
            ['name' => 'C32 AMG', 'parent_id' => 38],
            ['name' => 'C350', 'parent_id' => 38],
            ['name' => 'C36 AMG', 'parent_id' => 38],
            ['name' => 'C43 AMG', 'parent_id' => 38],
            ['name' => 'CL220', 'parent_id' => 38],
            ['name' => 'CL420', 'parent_id' => 38],
            ['name' => 'CL500', 'parent_id' => 38],
            ['name' => 'CL600', 'parent_id' => 38],
            ['name' => 'CL65 AMG', 'parent_id' => 38],
            ['name' => 'CLA180', 'parent_id' => 38],
            ['name' => 'CLA200', 'parent_id' => 38],
            ['name' => 'CLA220', 'parent_id' => 38],
            ['name' => 'CLA45 AMG', 'parent_id' => 38],
            ['name' => 'CLC180', 'parent_id' => 38],
            ['name' => 'CLC220', 'parent_id' => 38],
            ['name' => 'CLK200', 'parent_id' => 38],
            ['name' => 'CLK220', 'parent_id' => 38],
            ['name' => 'CLK230', 'parent_id' => 38],
            ['name' => 'CLK240', 'parent_id' => 38],
            ['name' => 'CLK270', 'parent_id' => 38],
            ['name' => 'CLK320', 'parent_id' => 38],
            ['name' => 'CLS250', 'parent_id' => 38],
            ['name' => 'CLS320', 'parent_id' => 38],
            ['name' => 'CLS350', 'parent_id' => 38],
            ['name' => 'CLS400', 'parent_id' => 38],
            ['name' => 'CLS500', 'parent_id' => 38],
            ['name' => 'CLS55 AMG', 'parent_id' => 38],
            ['name' => 'CLS63 AMG', 'parent_id' => 38],
            ['name' => 'E200', 'parent_id' => 38],
            ['name' => 'E220', 'parent_id' => 38],
            ['name' => 'E230', 'parent_id' => 38],
            ['name' => 'E240', 'parent_id' => 38],
            ['name' => 'E250', 'parent_id' => 38],
            ['name' => 'E260', 'parent_id' => 38],
            ['name' => 'E270', 'parent_id' => 38],
            ['name' => 'E280', 'parent_id' => 38],
            ['name' => 'E290', 'parent_id' => 38],
            ['name' => 'E300', 'parent_id' => 38],
            ['name' => 'E320', 'parent_id' => 38],
            ['name' => 'E350', 'parent_id' => 38],
            ['name' => 'E430', 'parent_id' => 38],
            ['name' => 'E55 AMG', 'parent_id' => 38],
            ['name' => 'E63 AMG', 'parent_id' => 38],
            ['name' => 'G230', 'parent_id' => 38],
            ['name' => 'G320', 'parent_id' => 38],
            ['name' => 'G350', 'parent_id' => 38],
            ['name' => 'GL350', 'parent_id' => 38],
            ['name' => 'GL420', 'parent_id' => 38],
            ['name' => 'GLA180', 'parent_id' => 38],
            ['name' => 'GLA200', 'parent_id' => 38],
            ['name' => 'GLA220', 'parent_id' => 38],
            ['name' => 'GLA45 AMG', 'parent_id' => 38],
            ['name' => 'GLK200', 'parent_id' => 38],
            ['name' => 'GLK220', 'parent_id' => 38],
            ['name' => 'GLK250', 'parent_id' => 38],
            ['name' => 'GLK320', 'parent_id' => 38],
            ['name' => 'GLK350', 'parent_id' => 38],
            ['name' => 'ML230', 'parent_id' => 38],
            ['name' => 'ML250', 'parent_id' => 38],
            ['name' => 'ML270', 'parent_id' => 38],
            ['name' => 'ML280', 'parent_id' => 38],
            ['name' => 'ML300', 'parent_id' => 38],
            ['name' => 'ML320', 'parent_id' => 38],
            ['name' => 'ML350', 'parent_id' => 38],
            ['name' => 'ML400', 'parent_id' => 38],
            ['name' => 'ML500', 'parent_id' => 38],
            ['name' => 'ML55 AMG', 'parent_id' => 38],
            ['name' => 'R280', 'parent_id' => 38],
            ['name' => 'R320', 'parent_id' => 38],
            ['name' => 'R350', 'parent_id' => 38],
            ['name' => 'S250', 'parent_id' => 38],
            ['name' => 'S300', 'parent_id' => 38],
            ['name' => 'S320', 'parent_id' => 38],
            ['name' => 'S350', 'parent_id' => 38],
            ['name' => 'S400', 'parent_id' => 38],
            ['name' => 'S420', 'parent_id' => 38],
            ['name' => 'S500', 'parent_id' => 38],
            ['name' => 'S600', 'parent_id' => 38],
            ['name' => 'SL320', 'parent_id' => 38],
            ['name' => 'SL350', 'parent_id' => 38],
            ['name' => 'SL400', 'parent_id' => 38],
            ['name' => 'SL500', 'parent_id' => 38],
            ['name' => 'SL55 AMG', 'parent_id' => 38],
            ['name' => 'SLK200', 'parent_id' => 38],
            ['name' => 'SLK230', 'parent_id' => 38],
            ['name' => 'SLK250', 'parent_id' => 38],
            ['name' => 'SLK280', 'parent_id' => 38],
            ['name' => 'SLK320', 'parent_id' => 38],
            ['name' => 'V220', 'parent_id' => 38],
            ['name' => 'V230', 'parent_id' => 38],
            ['name' => '180', 'parent_id' => 38],
            ['name' => '190', 'parent_id' => 38],
            ['name' => '200', 'parent_id' => 38],
            ['name' => '220', 'parent_id' => 38],
            ['name' => '230', 'parent_id' => 38],
            ['name' => '240', 'parent_id' => 38],
            ['name' => '250', 'parent_id' => 38],
            ['name' => '280', 'parent_id' => 38],
            ['name' => '300', 'parent_id' => 38],
            ['name' => '320', 'parent_id' => 38],
            ['name' => '350', 'parent_id' => 38],
            ['name' => '420', 'parent_id' => 38],
            ['name' => '500', 'parent_id' => 38],
            ['name' => '600', 'parent_id' => 38],
            ['name' => 'Citan 108', 'parent_id' => 38],
            ['name' => 'Citan 109', 'parent_id' => 38],
            ['name' => 'Sprinter', 'parent_id' => 38],
            ['name' => 'Vaneo', 'parent_id' => 38],
            ['name' => 'Viano', 'parent_id' => 38],
            ['name' => 'Vito', 'parent_id' => 38],

            // MG
            ['name' => 'TF', 'parent_id' => 39],
            ['name' => 'F', 'parent_id' => 39],
            ['name' => 'MGB', 'parent_id' => 39],
            ['name' => 'ZR', 'parent_id' => 39],
            ['name' => 'ZS', 'parent_id' => 39],
            ['name' => 'ZT', 'parent_id' => 39],
            ['name' => 'ZT-T', 'parent_id' => 39],

            // Mini
            ['name' => 'Clubman', 'parent_id' => 40],
            ['name' => 'Clubman Cooper S', 'parent_id' => 40],
            ['name' => 'Clubman One', 'parent_id' => 40],
            ['name' => 'Cooper', 'parent_id' => 40],
            ['name' => 'Cooper Cabriolet', 'parent_id' => 40],
            ['name' => 'Cooper S', 'parent_id' => 40],
            ['name' => 'Cooper S Cabriolet', 'parent_id' => 40],
            ['name' => 'Cooper S Works', 'parent_id' => 40],
            ['name' => 'Countryman', 'parent_id' => 40],
            ['name' => 'Countryman Cooper', 'parent_id' => 40],
            ['name' => 'Countryman One', 'parent_id' => 40],
            ['name' => 'One', 'parent_id' => 40],
            ['name' => 'One Cabriolet', 'parent_id' => 40],
            ['name' => 'Countryman', 'parent_id' => 40],
            ['name' => 'Coupé', 'parent_id' => 40],
            ['name' => 'Paceman', 'parent_id' => 40],

            // Mitsubishi
            ['name' => '3000', 'parent_id' => 41],
            ['name' => 'ASX', 'parent_id' => 41],
            ['name' => 'Canter', 'parent_id' => 41],
            ['name' => 'Carisma', 'parent_id' => 41],
            ['name' => 'Colt', 'parent_id' => 41],
            ['name' => 'Eclipse', 'parent_id' => 41],
            ['name' => 'Galant', 'parent_id' => 41],
            ['name' => 'Grandis', 'parent_id' => 41],
            ['name' => 'i-MiEV', 'parent_id' => 41],
            ['name' => 'L', 'parent_id' => 41],
            ['name' => 'L200', 'parent_id' => 41],
            ['name' => 'L300', 'parent_id' => 41],
            ['name' => 'L400', 'parent_id' => 41],
            ['name' => 'Lancer', 'parent_id' => 41],
            ['name' => 'Montero', 'parent_id' => 41],
            ['name' => 'Outlander', 'parent_id' => 41],
            ['name' => 'Outlander P-HEV', 'parent_id' => 41],
            ['name' => 'Pajero', 'parent_id' => 41],
            ['name' => 'Space Gear', 'parent_id' => 41],
            ['name' => 'Space Star', 'parent_id' => 41],
            ['name' => 'Space Wagon', 'parent_id' => 41],

            // Morgan
            ['name' => '4/4', 'parent_id' => 42],
            ['name' => 'Plus 4', 'parent_id' => 42],

            // Nissan
            ['name' => '100 NX', 'parent_id' => 43],
            ['name' => '200 SX', 'parent_id' => 43],
            ['name' => '300 ZX', 'parent_id' => 43],
            ['name' => '350Z', 'parent_id' => 43],
            ['name' => 'Almera', 'parent_id' => 43],
            ['name' => 'Bluebird', 'parent_id' => 43],
            ['name' => 'Cabstar', 'parent_id' => 43],
            ['name' => 'Cargo', 'parent_id' => 43],
            ['name' => 'GT-R', 'parent_id' => 43],
            ['name' => 'Interstar', 'parent_id' => 43],
            ['name' => 'Juke', 'parent_id' => 43],
            ['name' => 'King', 'parent_id' => 43],
            ['name' => 'Leaf', 'parent_id' => 43],
            ['name' => 'Maxima', 'parent_id' => 43],
            ['name' => 'Micra', 'parent_id' => 43],
            ['name' => 'Micra C+C', 'parent_id' => 43],
            ['name' => 'Murano', 'parent_id' => 43],
            ['name' => 'Navara', 'parent_id' => 43],
            ['name' => 'Navarra', 'parent_id' => 43],
            ['name' => 'Note', 'parent_id' => 43],
            ['name' => 'Pathfinder', 'parent_id' => 43],
            ['name' => 'Patrol', 'parent_id' => 43],
            ['name' => 'PickUp', 'parent_id' => 43],
            ['name' => 'Pixo', 'parent_id' => 43],
            ['name' => 'Prairie', 'parent_id' => 43],
            ['name' => 'Primastar', 'parent_id' => 43],
            ['name' => 'Primera', 'parent_id' => 43],
            ['name' => 'Pulsar', 'parent_id' => 43],
            ['name' => 'Qashqai', 'parent_id' => 43],
            ['name' => 'Qashqai +2', 'parent_id' => 43],
            ['name' => 'Sentra', 'parent_id' => 43],
            ['name' => 'Serena', 'parent_id' => 43],
            ['name' => 'Sunny', 'parent_id' => 43],
            ['name' => 'Terrano', 'parent_id' => 43],
            ['name' => 'Tiida', 'parent_id' => 43],
            ['name' => 'Trade', 'parent_id' => 43],
            ['name' => 'Urvan', 'parent_id' => 43],
            ['name' => 'Vanette', 'parent_id' => 43],
            ['name' => 'X-Trail', 'parent_id' => 43],

            // Opel
            ['name' => 'Adam', 'parent_id' => 44],
            ['name' => 'Agila', 'parent_id' => 44],
            ['name' => 'Ampera', 'parent_id' => 44],
            ['name' => 'Antara', 'parent_id' => 44],
            ['name' => 'Arena', 'parent_id' => 44],
            ['name' => 'Ascona', 'parent_id' => 44],
            ['name' => 'Astra', 'parent_id' => 44],
            ['name' => 'Astra Cabriolet', 'parent_id' => 44],
            ['name' => 'Astra Classic', 'parent_id' => 44],
            ['name' => 'Blitz', 'parent_id' => 44],
            ['name' => 'Calibra', 'parent_id' => 44],
            ['name' => 'Campo', 'parent_id' => 44],
            ['name' => 'Cascada', 'parent_id' => 44],
            ['name' => 'Combo', 'parent_id' => 44],
            ['name' => 'Commodore', 'parent_id' => 44],
            ['name' => 'Corsa', 'parent_id' => 44],
            ['name' => 'Frontera', 'parent_id' => 44],
            ['name' => 'GT', 'parent_id' => 44],
            ['name' => 'Insignia', 'parent_id' => 44],
            ['name' => 'Kadett', 'parent_id' => 44],
            ['name' => 'Kapitän', 'parent_id' => 44],
            ['name' => 'Manta', 'parent_id' => 44],
            ['name' => 'Meriva', 'parent_id' => 44],
            ['name' => 'Mokka', 'parent_id' => 44],
            ['name' => 'Monterey', 'parent_id' => 44],
            ['name' => 'Movano', 'parent_id' => 44],
            ['name' => 'Omega', 'parent_id' => 44],
            ['name' => 'Rekord', 'parent_id' => 44],
            ['name' => 'Signum', 'parent_id' => 44],
            ['name' => 'Tigra', 'parent_id' => 44],
            ['name' => 'Vectra', 'parent_id' => 44],
            ['name' => 'Vivaro', 'parent_id' => 44],
            ['name' => 'Zafira', 'parent_id' => 44],
            ['name' => 'Zafira Tourer', 'parent_id' => 44],

            // Peugeot
            ['name' => '1007', 'parent_id' => 45],
            ['name' => '104', 'parent_id' => 45],
            ['name' => '106', 'parent_id' => 45],
            ['name' => '107', 'parent_id' => 45],
            ['name' => '108', 'parent_id' => 45],
            ['name' => '2008', 'parent_id' => 45],
            ['name' => '204', 'parent_id' => 45],
            ['name' => '205', 'parent_id' => 45],
            ['name' => '206', 'parent_id' => 45],
            ['name' => '206+', 'parent_id' => 45],
            ['name' => '206 CC', 'parent_id' => 45],
            ['name' => '207', 'parent_id' => 45],
            ['name' => '207 CC', 'parent_id' => 45],
            ['name' => '207 Outdoor', 'parent_id' => 45],
            ['name' => '208', 'parent_id' => 45],
            ['name' => '3008', 'parent_id' => 45],
            ['name' => '304', 'parent_id' => 45],
            ['name' => '305', 'parent_id' => 45],
            ['name' => '306', 'parent_id' => 45],
            ['name' => '306 Cabriolet', 'parent_id' => 45],
            ['name' => '307', 'parent_id' => 45],
            ['name' => '307 CC', 'parent_id' => 45],
            ['name' => '308', 'parent_id' => 45],
            ['name' => '308 CC', 'parent_id' => 45],
            ['name' => '309', 'parent_id' => 45],
            ['name' => '4007', 'parent_id' => 45],
            ['name' => '404', 'parent_id' => 45],
            ['name' => '405', 'parent_id' => 45],
            ['name' => '406', 'parent_id' => 45],
            ['name' => '406 Coupe', 'parent_id' => 45],
            ['name' => '407', 'parent_id' => 45],
            ['name' => '407 Coupe', 'parent_id' => 45],
            ['name' => '5008', 'parent_id' => 45],
            ['name' => '504', 'parent_id' => 45],
            ['name' => '505', 'parent_id' => 45],
            ['name' => '508', 'parent_id' => 45],
            ['name' => '604', 'parent_id' => 45],
            ['name' => '605', 'parent_id' => 45],
            ['name' => '607', 'parent_id' => 45],
            ['name' => '806', 'parent_id' => 45],
            ['name' => '807', 'parent_id' => 45],
            ['name' => 'Bipper', 'parent_id' => 45],
            ['name' => 'Boxer', 'parent_id' => 45],
            ['name' => 'Expert', 'parent_id' => 45],
            ['name' => 'iON', 'parent_id' => 45],
            ['name' => 'J5', 'parent_id' => 45],
            ['name' => 'Partner', 'parent_id' => 45],
            ['name' => 'Partner Tepee', 'parent_id' => 45],
            ['name' => 'RCZ', 'parent_id' => 45],

            // Piaggio
            ['name' => 'Porter', 'parent_id' => 46],

            // Pontiac
            ['name' => 'Firebird', 'parent_id' => 47],
            ['name' => 'Sunbird', 'parent_id' => 47],

            // Porshe
            ['name' => '911', 'parent_id' => 48],
            ['name' => '911 Carrera', 'parent_id' => 48],
            ['name' => '911 Carrera 4', 'parent_id' => 48],
            ['name' => '911 Carrera 4S', 'parent_id' => 48],
            ['name' => '911 Carrera S', 'parent_id' => 48],
            ['name' => '911 Targa 4', 'parent_id' => 48],
            ['name' => '911 Turbo', 'parent_id' => 48],
            ['name' => '911 Turbo S', 'parent_id' => 48],
            ['name' => '996', 'parent_id' => 48],
            ['name' => '997', 'parent_id' => 48],
            ['name' => 'Boxster', 'parent_id' => 48],
            ['name' => 'Boxster GTS', 'parent_id' => 48],
            ['name' => 'Boxster S', 'parent_id' => 48],
            ['name' => 'Cayenne', 'parent_id' => 48],
            ['name' => 'Cayenne GTS', 'parent_id' => 48],
            ['name' => 'Cayenne S', 'parent_id' => 48],
            ['name' => 'Cayenne S Hybrid', 'parent_id' => 48],
            ['name' => 'Cayenne Turbo', 'parent_id' => 48],
            ['name' => 'Cayman', 'parent_id' => 48],
            ['name' => 'Macan', 'parent_id' => 48],
            ['name' => 'Macan S', 'parent_id' => 48],
            ['name' => 'Panamera', 'parent_id' => 48],
            ['name' => 'Panamera 4', 'parent_id' => 48],
            ['name' => 'Panamera 4S', 'parent_id' => 48],
            ['name' => 'Panamera S', 'parent_id' => 48],
            ['name' => 'Panamera Turbo', 'parent_id' => 48],
            ['name' => '914', 'parent_id' => 48],
            ['name' => '924', 'parent_id' => 48],
            ['name' => '928', 'parent_id' => 48],
            ['name' => '944', 'parent_id' => 48],
            ['name' => '968', 'parent_id' => 48],

            // Renault
            ['name' => 'Clio', 'parent_id' => 49],
            ['name' => 'Clio GT', 'parent_id' => 49],
            ['name' => 'Clio II', 'parent_id' => 49],
            ['name' => 'Clio III', 'parent_id' => 49],
            ['name' => 'Clio IV', 'parent_id' => 49],
            ['name' => 'Espace', 'parent_id' => 49],
            ['name' => 'Grand Espace', 'parent_id' => 49],
            ['name' => 'Grand Modus', 'parent_id' => 49],
            ['name' => 'Modus', 'parent_id' => 49],
            ['name' => 'Grand Scénic', 'parent_id' => 49],
            ['name' => 'Grand Scénic II', 'parent_id' => 49],
            ['name' => 'Grand Scénic III', 'parent_id' => 49],
            ['name' => 'Scénic', 'parent_id' => 49],
            ['name' => 'Scénic II', 'parent_id' => 49],
            ['name' => 'Scénic III', 'parent_id' => 49],
            ['name' => 'Scénic Xmod', 'parent_id' => 49],
            ['name' => 'Laguna', 'parent_id' => 49],
            ['name' => 'Laguna Coupé', 'parent_id' => 49],
            ['name' => 'Laguna II', 'parent_id' => 49],
            ['name' => 'Laguna III', 'parent_id' => 49],
            ['name' => 'Mégane', 'parent_id' => 49],
            ['name' => 'Mégane Cabriolet', 'parent_id' => 49],
            ['name' => 'Mégane Coupé', 'parent_id' => 49],
            ['name' => 'Mégane GT', 'parent_id' => 49],
            ['name' => 'Mégane II', 'parent_id' => 49],
            ['name' => 'Mégane III', 'parent_id' => 49],
            ['name' => 'R4', 'parent_id' => 49],
            ['name' => 'R5', 'parent_id' => 49],
            ['name' => '19', 'parent_id' => 49],
            ['name' => 'Avantime', 'parent_id' => 49],
            ['name' => 'Captur', 'parent_id' => 49],
            ['name' => 'Express', 'parent_id' => 49],
            ['name' => 'Fluence', 'parent_id' => 49],
            ['name' => 'Kangoo', 'parent_id' => 49],
            ['name' => 'Koleos', 'parent_id' => 49],
            ['name' => 'Master', 'parent_id' => 49],
            ['name' => 'Rapid', 'parent_id' => 49],
            ['name' => 'Safrane', 'parent_id' => 49],
            ['name' => 'Trafic', 'parent_id' => 49],
            ['name' => 'Twingo', 'parent_id' => 49],
            ['name' => 'Twizy', 'parent_id' => 49],
            ['name' => 'Vel Satis', 'parent_id' => 49],
            ['name' => 'Zoe', 'parent_id' => 49],

            // Rolls Royce
            ['name' => 'Silver Spirit', 'parent_id' => 50],
            ['name' => 'Silver Spur', 'parent_id' => 50],

            // Rover
            ['name' => '100', 'parent_id' => 51],
            ['name' => '111', 'parent_id' => 51],
            ['name' => '200', 'parent_id' => 51],
            ['name' => '213', 'parent_id' => 51],
            ['name' => '214', 'parent_id' => 51],
            ['name' => '216', 'parent_id' => 51],
            ['name' => '220', 'parent_id' => 51],
            ['name' => '25', 'parent_id' => 51],
            ['name' => '400', 'parent_id' => 51],
            ['name' => '414', 'parent_id' => 51],
            ['name' => '416', 'parent_id' => 51],
            ['name' => '420', 'parent_id' => 51],
            ['name' => '45', 'parent_id' => 51],
            ['name' => '600', 'parent_id' => 51],
            ['name' => '620', 'parent_id' => 51],
            ['name' => '75', 'parent_id' => 51],
            ['name' => '820', 'parent_id' => 51],
            ['name' => 'City Rover', 'parent_id' => 51],
            ['name' => 'Streetwise', 'parent_id' => 51],

            // Saab
            ['name' => '900', 'parent_id' => 52],
            ['name' => '9000', 'parent_id' => 52],
            ['name' => '900 Cabriolet', 'parent_id' => 52],
            ['name' => '9-3', 'parent_id' => 52],
            ['name' => '9-3 Cabriolet', 'parent_id' => 52],
            ['name' => '9-3X', 'parent_id' => 52],
            ['name' => '9-5', 'parent_id' => 52],
            ['name' => '9-7X', 'parent_id' => 52],

            // Seat
            ['name' => 'Alhambra', 'parent_id' => 53],
            ['name' => 'Altea', 'parent_id' => 53],
            ['name' => 'Altea XL', 'parent_id' => 53],
            ['name' => 'Arosa', 'parent_id' => 53],
            ['name' => 'Cordoba', 'parent_id' => 53],
            ['name' => 'Exeo', 'parent_id' => 53],
            ['name' => 'Ibiza', 'parent_id' => 53],
            ['name' => 'Inca', 'parent_id' => 53],
            ['name' => 'Leon', 'parent_id' => 53],
            ['name' => 'Marbella', 'parent_id' => 53],
            ['name' => 'Mii', 'parent_id' => 53],
            ['name' => 'Toledo', 'parent_id' => 53],

            // Skoda
            ['name' => '105', 'parent_id' => 54],
            ['name' => 'Fabia', 'parent_id' => 54],
            ['name' => 'Favorit', 'parent_id' => 54],
            ['name' => 'Felicia', 'parent_id' => 54],
            ['name' => 'Octavia', 'parent_id' => 54],
            ['name' => 'Rapid', 'parent_id' => 54],
            ['name' => 'Rapid Spaceback', 'parent_id' => 54],
            ['name' => 'Roomster', 'parent_id' => 54],
            ['name' => 'Superb', 'parent_id' => 54],
            ['name' => 'Yeti', 'parent_id' => 54],

            // Smart
            ['name' => 'ForTwo Cabrio', 'parent_id' => 55],
            ['name' => 'ForTwo Coupé', 'parent_id' => 55],
            ['name' => 'City Cabrio', 'parent_id' => 55],
            ['name' => 'City Coupé', 'parent_id' => 55],
            ['name' => 'Crossblade', 'parent_id' => 55],
            ['name' => 'ForFour', 'parent_id' => 55],
            ['name' => 'Roadster Coupé', 'parent_id' => 55],

            // Ssangyong
            ['name' => 'Actyon', 'parent_id' => 56],
            ['name' => 'Korando', 'parent_id' => 56],
            ['name' => 'Musso', 'parent_id' => 56],

            // Subaru
            ['name' => 'Forester', 'parent_id' => 57],
            ['name' => 'Impreza', 'parent_id' => 57],
            ['name' => 'Legacy', 'parent_id' => 57],
            ['name' => 'Outback', 'parent_id' => 57],

            // Suzuki
            ['name' => 'Alto', 'parent_id' => 58],
            ['name' => 'Baleno', 'parent_id' => 58],
            ['name' => 'Grand Vitara', 'parent_id' => 58],
            ['name' => 'Ignis', 'parent_id' => 58],
            ['name' => 'Jimny', 'parent_id' => 58],
            ['name' => 'Liana', 'parent_id' => 58],
            ['name' => 'Samurai', 'parent_id' => 58],
            ['name' => 'S-Cross', 'parent_id' => 58],
            ['name' => 'Splash', 'parent_id' => 58],
            ['name' => 'Swift', 'parent_id' => 58],
            ['name' => 'SX4', 'parent_id' => 58],
            ['name' => 'Vitara', 'parent_id' => 58],
            ['name' => 'Wagon R', 'parent_id' => 58],
            ['name' => 'Wagon R+', 'parent_id' => 58],

            // Tata
            ['name' => 'Indica', 'parent_id' => 59],

            // Toyota
            ['name' => '4Runner', 'parent_id' => 60],
            ['name' => 'Auris', 'parent_id' => 60],
            ['name' => 'Avensis', 'parent_id' => 60],
            ['name' => 'Avensis Verso', 'parent_id' => 60],
            ['name' => 'Aygo', 'parent_id' => 60],
            ['name' => 'Camry', 'parent_id' => 60],
            ['name' => 'Carina', 'parent_id' => 60],
            ['name' => 'Carina E', 'parent_id' => 60],
            ['name' => 'Carina II', 'parent_id' => 60],
            ['name' => 'Celica', 'parent_id' => 60],
            ['name' => 'Corolla', 'parent_id' => 60],
            ['name' => 'Corolla Verso', 'parent_id' => 60],
            ['name' => 'Cressida', 'parent_id' => 60],
            ['name' => 'Crown', 'parent_id' => 60],
            ['name' => 'Dyna', 'parent_id' => 60],
            ['name' => 'HiAce', 'parent_id' => 60],
            ['name' => 'Highlander Hybrid', 'parent_id' => 60],
            ['name' => 'HiLux', 'parent_id' => 60],
            ['name' => 'iQ', 'parent_id' => 60],
            ['name' => 'Landcruiser', 'parent_id' => 60],
            ['name' => 'Lite-Ace', 'parent_id' => 60],
            ['name' => 'MR2', 'parent_id' => 60],
            ['name' => 'Paseo', 'parent_id' => 60],
            ['name' => 'Previa', 'parent_id' => 60],
            ['name' => 'Prius', 'parent_id' => 60],
            ['name' => 'Prius+', 'parent_id' => 60],
            ['name' => 'RAV4', 'parent_id' => 60],
            ['name' => 'Starlet', 'parent_id' => 60],
            ['name' => 'Supra', 'parent_id' => 60],
            ['name' => 'Tundra', 'parent_id' => 60],
            ['name' => 'Urban Cruiser', 'parent_id' => 60],
            ['name' => 'Verso', 'parent_id' => 60],
            ['name' => 'Verso-S', 'parent_id' => 60],
            ['name' => 'Yaris', 'parent_id' => 60],
            ['name' => 'Yaris Verso', 'parent_id' => 60],

            // Triumph
            ['name' => 'Spitfire', 'parent_id' => 61],

            // Volvo
            ['name' => '140', 'parent_id' => 62],
            ['name' => '164', 'parent_id' => 62],
            ['name' => '240', 'parent_id' => 62],
            ['name' => '340', 'parent_id' => 62],
            ['name' => '440', 'parent_id' => 62],
            ['name' => '460', 'parent_id' => 62],
            ['name' => '480', 'parent_id' => 62],
            ['name' => '740', 'parent_id' => 62],
            ['name' => '850', 'parent_id' => 62],
            ['name' => '940', 'parent_id' => 62],
            ['name' => '960', 'parent_id' => 62],
            ['name' => 'C30', 'parent_id' => 62],
            ['name' => 'C70', 'parent_id' => 62],
            ['name' => 'S40', 'parent_id' => 62],
            ['name' => 'S60', 'parent_id' => 62],
            ['name' => 'S70', 'parent_id' => 62],
            ['name' => 'S80', 'parent_id' => 62],
            ['name' => 'V40', 'parent_id' => 62],
            ['name' => 'V40 CC', 'parent_id' => 62],
            ['name' => 'V50', 'parent_id' => 62],
            ['name' => 'V60', 'parent_id' => 62],
            ['name' => 'V60 CC', 'parent_id' => 62],
            ['name' => 'V70', 'parent_id' => 62],
            ['name' => 'XC60', 'parent_id' => 62],
            ['name' => 'XC70', 'parent_id' => 62],
            ['name' => 'XC90', 'parent_id' => 62],

            // Volkswagen
            ['name' => 'Golf', 'parent_id' => 63],
            ['name' => 'Golf Cabriolet', 'parent_id' => 63],
            ['name' => 'Golf I', 'parent_id' => 63],
            ['name' => 'Golf II', 'parent_id' => 63],
            ['name' => 'Golf III', 'parent_id' => 63],
            ['name' => 'Golf IV', 'parent_id' => 63],
            ['name' => 'Golf Plus', 'parent_id' => 63],
            ['name' => 'Golf Sportsvan', 'parent_id' => 63],
            ['name' => 'Golf V', 'parent_id' => 63],
            ['name' => 'Golf VI', 'parent_id' => 63],
            ['name' => 'Golf VII', 'parent_id' => 63],
            ['name' => 'Amarok', 'parent_id' => 63],
            ['name' => 'Beetle', 'parent_id' => 63],
            ['name' => 'Bora', 'parent_id' => 63],
            ['name' => 'Buggy', 'parent_id' => 63],
            ['name' => 'Caddy', 'parent_id' => 63],
            ['name' => 'California', 'parent_id' => 63],
            ['name' => 'Caravelle', 'parent_id' => 63],
            ['name' => 'Corrado', 'parent_id' => 63],
            ['name' => 'Crafter', 'parent_id' => 63],
            ['name' => 'Eos', 'parent_id' => 63],
            ['name' => 'Fox', 'parent_id' => 63],
            ['name' => 'Jetta', 'parent_id' => 63],
            ['name' => 'Karmann Ghia', 'parent_id' => 63],
            ['name' => 'LT', 'parent_id' => 63],
            ['name' => 'Lupo', 'parent_id' => 63],
            ['name' => 'Multivan', 'parent_id' => 63],
            ['name' => 'Passat', 'parent_id' => 63],
            ['name' => 'Passat CC', 'parent_id' => 63],
            ['name' => 'Phaeton', 'parent_id' => 63],
            ['name' => 'Polo', 'parent_id' => 63],
            ['name' => 'Polo Cross', 'parent_id' => 63],
            ['name' => 'Scirocco', 'parent_id' => 63],
            ['name' => 'Sharan', 'parent_id' => 63],
            ['name' => 'Shuttle', 'parent_id' => 63],
            ['name' => 'Tiguan', 'parent_id' => 63],
            ['name' => 'Touareg', 'parent_id' => 63],
            ['name' => 'Touran', 'parent_id' => 63],
            ['name' => 'Transporter', 'parent_id' => 63],
            ['name' => 'UP!', 'parent_id' => 63],
            ['name' => 'Vento', 'parent_id' => 63],

        ];

        DB::table('vehicles_makes_models')->insert($makes);
        DB::table('vehicles_makes_models')->insert($models);
    }
}
