<?php

/*
 * This file is part of Bens Penhorados, an undergraduate capstone project.
 *
 * (c) Fábio Santos <ffsantos92@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace VehicleModels;

use DB;
use Illuminate\Database\Seeder;

class Mercedes extends Seeder
{
    public function run()
    {
        $makeId = DB::table('vehicle_makes')->where('name', 'Mercedes')->pluck('id');

        $models = [
            ['name' => 'A140', 'regex' => '/a140/i', 'make_id' => $makeId],
            ['name' => 'A150', 'regex' => '/a150/i', 'make_id' => $makeId],
            ['name' => 'A160', 'regex' => '/a160/i', 'make_id' => $makeId],
            ['name' => 'A170', 'regex' => '/a170/i', 'make_id' => $makeId],
            ['name' => 'A180', 'regex' => '/a180/i', 'make_id' => $makeId],
            ['name' => 'A190', 'regex' => '/a190/i', 'make_id' => $makeId],
            ['name' => 'A200', 'regex' => '/a200/i', 'make_id' => $makeId],
            ['name' => 'A220', 'regex' => '/a220/i', 'make_id' => $makeId],
            ['name' => 'A250', 'regex' => '/a250/i', 'make_id' => $makeId],
            ['name' => 'A45 AMG', 'regex' => '/a45[\pP\s]?amg/i', 'make_id' => $makeId],
            ['name' => 'B150', 'regex' => '/b150/i', 'make_id' => $makeId],
            ['name' => 'B160', 'regex' => '/b160/i', 'make_id' => $makeId],
            ['name' => 'B170', 'regex' => '/b170/i', 'make_id' => $makeId],
            ['name' => 'B180', 'regex' => '/b180/i', 'make_id' => $makeId],
            ['name' => 'B200', 'regex' => '/b200/i', 'make_id' => $makeId],
            ['name' => 'C180', 'regex' => '/c180/i', 'make_id' => $makeId],
            ['name' => 'C200', 'regex' => '/c200/i', 'make_id' => $makeId],
            ['name' => 'C220', 'regex' => '/c220/i', 'make_id' => $makeId],
            ['name' => 'C230', 'regex' => '/c230/i', 'make_id' => $makeId],
            ['name' => 'C250', 'regex' => '/c250/i', 'make_id' => $makeId],
            ['name' => 'C270', 'regex' => '/c270/i', 'make_id' => $makeId],
            ['name' => 'C280', 'regex' => '/c280/i', 'make_id' => $makeId],
            ['name' => 'C300', 'regex' => '/c300/i', 'make_id' => $makeId],
            ['name' => 'C30 AMG', 'regex' => '/c30[\pP\s]?amg/i', 'make_id' => $makeId],
            ['name' => 'C320', 'regex' => '/c320/i', 'make_id' => $makeId],
            ['name' => 'C32 AMG', 'regex' => '/c32[\pP\s]?amg/i', 'make_id' => $makeId],
            ['name' => 'C350', 'regex' => '/c350/i', 'make_id' => $makeId],
            ['name' => 'C36 AMG', 'regex' => '/c36[\pP\s]?amg/i', 'make_id' => $makeId],
            ['name' => 'C43 AMG', 'regex' => '/c43[\pP\s]?amg/i', 'make_id' => $makeId],
            ['name' => 'CL220', 'regex' => '/cl220/i', 'make_id' => $makeId],
            ['name' => 'CL420', 'regex' => '/cl420/i', 'make_id' => $makeId],
            ['name' => 'CL500', 'regex' => '/cl500/i', 'make_id' => $makeId],
            ['name' => 'CL600', 'regex' => '/cl600/i', 'make_id' => $makeId],
            ['name' => 'CL65 AMG', 'regex' => '/cl65[\pP\s]?amg/i', 'make_id' => $makeId],
            ['name' => 'CLA180', 'regex' => '/cla180/i', 'make_id' => $makeId],
            ['name' => 'CLA200', 'regex' => '/cla200/i', 'make_id' => $makeId],
            ['name' => 'CLA220', 'regex' => '/cla220/i', 'make_id' => $makeId],
            ['name' => 'CLA45 AMG', 'regex' => '/cla45[\pP\s]?amg/i', 'make_id' => $makeId],
            ['name' => 'CLC180', 'regex' => '/clc180/i', 'make_id' => $makeId],
            ['name' => 'CLC220', 'regex' => '/clc220/i', 'make_id' => $makeId],
            ['name' => 'CLK200', 'regex' => '/clk200/i', 'make_id' => $makeId],
            ['name' => 'CLK220', 'regex' => '/clk220/i', 'make_id' => $makeId],
            ['name' => 'CLK230', 'regex' => '/clk230/i', 'make_id' => $makeId],
            ['name' => 'CLK240', 'regex' => '/clk240/i', 'make_id' => $makeId],
            ['name' => 'CLK270', 'regex' => '/clk270/i', 'make_id' => $makeId],
            ['name' => 'CLK320', 'regex' => '/clk320/i', 'make_id' => $makeId],
            ['name' => 'CLS250', 'regex' => '/cls250/i', 'make_id' => $makeId],
            ['name' => 'CLS320', 'regex' => '/cls320/i', 'make_id' => $makeId],
            ['name' => 'CLS350', 'regex' => '/cls350/i', 'make_id' => $makeId],
            ['name' => 'CLS400', 'regex' => '/cls400/i', 'make_id' => $makeId],
            ['name' => 'CLS500', 'regex' => '/cls500/i', 'make_id' => $makeId],
            ['name' => 'CLS55 AMG', 'regex' => '/cls55[\pP\s]?amg/i', 'make_id' => $makeId],
            ['name' => 'CLS63 AMG', 'regex' => '/cls63[\pP\s]?amg/i', 'make_id' => $makeId],
            ['name' => 'E200', 'regex' => '/e200/i', 'make_id' => $makeId],
            ['name' => 'E220', 'regex' => '/e220/i', 'make_id' => $makeId],
            ['name' => 'E230', 'regex' => '/e230/i', 'make_id' => $makeId],
            ['name' => 'E240', 'regex' => '/e240/i', 'make_id' => $makeId],
            ['name' => 'E250', 'regex' => '/e250/i', 'make_id' => $makeId],
            ['name' => 'E260', 'regex' => '/e260/i', 'make_id' => $makeId],
            ['name' => 'E270', 'regex' => '/e270/i', 'make_id' => $makeId],
            ['name' => 'E280', 'regex' => '/e280/i', 'make_id' => $makeId],
            ['name' => 'E290', 'regex' => '/e290/i', 'make_id' => $makeId],
            ['name' => 'E300', 'regex' => '/e300/i', 'make_id' => $makeId],
            ['name' => 'E320', 'regex' => '/e320/i', 'make_id' => $makeId],
            ['name' => 'E350', 'regex' => '/e350/i', 'make_id' => $makeId],
            ['name' => 'E430', 'regex' => '/e430/i', 'make_id' => $makeId],
            ['name' => 'E55 AMG', 'regex' => '/e55[\pP\s]?amg/i', 'make_id' => $makeId],
            ['name' => 'E63 AMG', 'regex' => '/e63[\pP\s]?amg/i', 'make_id' => $makeId],
            ['name' => 'G230', 'regex' => '/g230/i', 'make_id' => $makeId],
            ['name' => 'G320', 'regex' => '/g320/i', 'make_id' => $makeId],
            ['name' => 'G350', 'regex' => '/g350/i', 'make_id' => $makeId],
            ['name' => 'GL350', 'regex' => '/gl350/i', 'make_id' => $makeId],
            ['name' => 'GL420', 'regex' => '/gl420/i', 'make_id' => $makeId],
            ['name' => 'GLA180', 'regex' => '/gla180/i', 'make_id' => $makeId],
            ['name' => 'GLA200', 'regex' => '/gla200/i', 'make_id' => $makeId],
            ['name' => 'GLA220', 'regex' => '/gla220/i', 'make_id' => $makeId],
            ['name' => 'GLA45 AMG', 'regex' => '/gla45[\pP\s]?amg/i', 'make_id' => $makeId],
            ['name' => 'GLK200', 'regex' => '/glk200/i', 'make_id' => $makeId],
            ['name' => 'GLK220', 'regex' => '/glk220/i', 'make_id' => $makeId],
            ['name' => 'GLK250', 'regex' => '/glk250/i', 'make_id' => $makeId],
            ['name' => 'GLK320', 'regex' => '/glk320/i', 'make_id' => $makeId],
            ['name' => 'GLK350', 'regex' => '/glk350/i', 'make_id' => $makeId],
            ['name' => 'ML230', 'regex' => '/ml230/i', 'make_id' => $makeId],
            ['name' => 'ML250', 'regex' => '/ml250/i', 'make_id' => $makeId],
            ['name' => 'ML270', 'regex' => '/ml270/i', 'make_id' => $makeId],
            ['name' => 'ML280', 'regex' => '/ml280/i', 'make_id' => $makeId],
            ['name' => 'ML300', 'regex' => '/ml300/i', 'make_id' => $makeId],
            ['name' => 'ML320', 'regex' => '/ml320/i', 'make_id' => $makeId],
            ['name' => 'ML350', 'regex' => '/ml350/i', 'make_id' => $makeId],
            ['name' => 'ML400', 'regex' => '/ml400/i', 'make_id' => $makeId],
            ['name' => 'ML500', 'regex' => '/ml500/i', 'make_id' => $makeId],
            ['name' => 'ML55 AMG', 'regex' => '/ml55[\pP\s]?amg/i', 'make_id' => $makeId],
            ['name' => 'R280', 'regex' => '/r280/i', 'make_id' => $makeId],
            ['name' => 'R320', 'regex' => '/r320/i', 'make_id' => $makeId],
            ['name' => 'R350', 'regex' => '/r350/i', 'make_id' => $makeId],
            ['name' => 'S250', 'regex' => '/s250/i', 'make_id' => $makeId],
            ['name' => 'S300', 'regex' => '/s300/i', 'make_id' => $makeId],
            ['name' => 'S320', 'regex' => '/s320/i', 'make_id' => $makeId],
            ['name' => 'S350', 'regex' => '/s350/i', 'make_id' => $makeId],
            ['name' => 'S400', 'regex' => '/s400/i', 'make_id' => $makeId],
            ['name' => 'S420', 'regex' => '/s420/i', 'make_id' => $makeId],
            ['name' => 'S500', 'regex' => '/s500/i', 'make_id' => $makeId],
            ['name' => 'S600', 'regex' => '/s600/i', 'make_id' => $makeId],
            ['name' => 'SL320', 'regex' => '/sl320/i', 'make_id' => $makeId],
            ['name' => 'SL350', 'regex' => '/sl350/i', 'make_id' => $makeId],
            ['name' => 'SL400', 'regex' => '/sl400/i', 'make_id' => $makeId],
            ['name' => 'SL500', 'regex' => '/sl500/i', 'make_id' => $makeId],
            ['name' => 'SL55 AMG', 'regex' => '/sl55[\pP\s]?amg/i', 'make_id' => $makeId],
            ['name' => 'SLK200', 'regex' => '/slk200/i', 'make_id' => $makeId],
            ['name' => 'SLK230', 'regex' => '/slk230/i', 'make_id' => $makeId],
            ['name' => 'SLK250', 'regex' => '/slk250/i', 'make_id' => $makeId],
            ['name' => 'SLK280', 'regex' => '/slk280/i', 'make_id' => $makeId],
            ['name' => 'SLK320', 'regex' => '/slk320/i', 'make_id' => $makeId],
            ['name' => 'V220', 'regex' => '/v220/i', 'make_id' => $makeId],
            ['name' => 'V230', 'regex' => '/v230/i', 'make_id' => $makeId],
            ['name' => '180', 'regex' => '/180/', 'make_id' => $makeId],
            ['name' => '190', 'regex' => '/190/', 'make_id' => $makeId],
            ['name' => '200', 'regex' => '/200/', 'make_id' => $makeId],
            ['name' => '220', 'regex' => '/220/', 'make_id' => $makeId],
            ['name' => '230', 'regex' => '/230/', 'make_id' => $makeId],
            ['name' => '240', 'regex' => '/240/', 'make_id' => $makeId],
            ['name' => '250', 'regex' => '/250/', 'make_id' => $makeId],
            ['name' => '280', 'regex' => '/280/', 'make_id' => $makeId],
            ['name' => '300', 'regex' => '/300/', 'make_id' => $makeId],
            ['name' => '320', 'regex' => '/320/', 'make_id' => $makeId],
            ['name' => '350', 'regex' => '/350/', 'make_id' => $makeId],
            ['name' => '420', 'regex' => '/420/', 'make_id' => $makeId],
            ['name' => '500', 'regex' => '/500/', 'make_id' => $makeId],
            ['name' => '600', 'regex' => '/600/', 'make_id' => $makeId],
            ['name' => 'Citan 108', 'regex' => '/citan[\pP\s]?108/i', 'make_id' => $makeId],
            ['name' => 'Citan 109', 'regex' => '/citan[\pP\s]?109/i', 'make_id' => $makeId],
            ['name' => 'Sprinter', 'regex' => '/sprinter/i', 'make_id' => $makeId],
            ['name' => 'Vaneo', 'regex' => '/vaneo/i', 'make_id' => $makeId],
            ['name' => 'Viano', 'regex' => '/viano/i', 'make_id' => $makeId],
            ['name' => 'Vito', 'regex' => '/vito/i', 'make_id' => $makeId],
        ];

        DB::table('vehicle_models')->insert($models);
    }
}
